"""Hand-crafted enrichment + storyline for EWCA Civ 2024 batch 1 (manual, not generated)."""

CASES = [
    {
        "source_path": "data/judgments/ewca/civ/2024/1.json",
        "judges": ["Lord Justice Nugee", "Lord Justice Newey", "Lord Justice Peter Jackson"],
        "enrichment": {
            "short_title": "Offshore oil hire cap and incidental accommodation use",
            "area_of_law": ["Tax law", "Corporation tax", "Oil and gas", "Statutory interpretation"],
            "statutes_considered": [
                {"title": "Corporation Tax Act 2010", "provisions": ["Part 8ZA", "section 356LA", "section 356N"]},
                {"title": "Finance Act 2014", "provisions": ["section 73", "Schedule 16"]},
                {"title": "Petroleum Act 1998", "provisions": ["Part 1"]},
            ],
            "key_facts": [
                "Dolphin Drilling leased the Borgsten from an associated Singapore company and provided tender-assisted drilling services to Total at the Dunbar platform.",
                "Part 8ZA CTA 2010 imposes a hire cap on payments for relevant assets leased from associated persons in the offshore oil sector from 1 April 2014.",
                "An asset is a relevant asset if it can provide accommodation for offshore workers unless that use is unlikely to be more than incidental to another use.",
                "HMRC amended Dolphin's returns; the FTT and UT held accommodation use was incidental, but the Court of Appeal reversed on the meaning of incidental.",
            ],
            "procedural_posture": "HMRC appeal with permission of Lewison LJ from the Upper Tribunal, which had upheld the First-tier Tribunal.",
            "outcome": "Appeal allowed; the hire cap applies because use of the Borgsten to accommodate Dunbar workers was not merely incidental to its TAD services.",
            "ratio": "For section 356LA(3) CTA 2010, one use is incidental to another only if it arises out of, is connected with, or is a by-product of that other use — not merely because it is secondary in importance. Accommodating Total personnel on the Borgsten was a significant independent use, not incidental to providing TAD services.",
            "legal_issues": [
                "Meaning of incidental in section 356LA(3) CTA 2010",
                "Whether FTT misdirected itself by comparing relative importance of uses rather than their connection",
                "Timing of the reasonable-to-suppose assessment for accounting periods straddling pre-drilling and drilling phases",
            ],
            "catchwords": ["hire cap", "relevant asset", "offshore workers", "incidental use", "bareboat charter", "ring fence profits"],
            "index_terms": ["Dolphin Drilling", "Borgsten", "Dunbar platform", "TAD services", "Total E&P UK", "Part 8ZA"],
            "linked_authorities": ["Robson v Dixon", "Proctor & Gamble UK v HMRC"],
            "confidence": {
                "score": 0.91,
                "level": "high",
                "notes": "Ratio, facts and panel (Nugee, Newey and Peter Jackson LJJ) are explicit in the judgment.",
            },
            "storyline": {
                "title": "HMRC caps bareboat hire after Borgsten accommodation ruled non-incidental",
                "summary": "Dolphin Drilling challenged HMRC hire-cap assessments on payments for the Borgsten, a converted rig moored alongside Total's Dunbar platform. Tribunals held worker accommodation was incidental to tender support services, but the Court of Appeal held incidental means connected, not merely secondary — restoring multi-million-pound tax liabilities.",
                "span": {"start": "2011-06-01", "end": "2024-01-01", "label": "June 2011 – January 2024"},
                "parties": [
                    {"role": "appellant", "name": "Commissioners for HMRC", "short_name": "HMRC"},
                    {"role": "respondent", "name": "Dolphin Drilling Ltd", "short_name": "Dolphin"},
                    {"role": "authority", "name": "Total E&P UK Ltd", "short_name": "Total"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "borgsten-contract", "order": 1, "date": "2011-11-10", "date_label": "10 November 2011", "date_precision": "exact", "title": "Dolphin wins Dunbar TSV contract", "category": "factual", "actor": "Dolphin Drilling / Total", "what_happened": "Total awarded Dolphin the contract to supply tender-assisted drilling services using the Borgsten alongside the Dunbar platform.", "why_it_matters": "Established the operational setting in which accommodation and TAD services would coexist.", "legal_hook": None},
                    {"id": "borgsten-moored", "order": 2, "date": "2013-02-01", "date_label": "February 2013", "date_precision": "month", "title": "Borgsten connected to Dunbar", "category": "factual", "actor": "Dolphin Drilling", "what_happened": "The Borgsten moved into position and began providing services through an extended pre-drilling phase.", "why_it_matters": "Average of 58–59 Total personnel slept on the Borgsten during 2014.", "legal_hook": None},
                    {"id": "hire-cap-enacted", "order": 3, "date": "2014-04-01", "date_label": "1 April 2014", "date_precision": "exact", "title": "Part 8ZA hire cap takes effect", "category": "institutional", "actor": "Parliament / HMRC", "what_happened": "New oil contractor ring-fence rules including the hire cap applied from this date.", "why_it_matters": "Triggered the statutory question whether the Borgsten was a relevant asset.", "legal_hook": "Finance Act 2014; CTA 2010 Part 8ZA"},
                    {"id": "hmrc-assessment", "order": 4, "date": "2018-01-15", "date_label": "15 January 2018", "date_precision": "exact", "title": "HMRC issues closure notices", "category": "institutional", "actor": "HMRC", "what_happened": "HMRC amended Dolphin's corporation tax returns for 2014 and 2015, imposing additional tax of over £6.7m.", "why_it_matters": "Started the formal dispute on whether the hire cap applied.", "legal_hook": "CTA 2010 section 356N"},
                    {"id": "ftt-victory", "order": 5, "date": "2020-11-16", "date_label": "16 November 2020", "date_precision": "exact", "title": "First-tier Tribunal allows Dolphin's appeal", "category": "decision", "actor": "FTT (Zaman J, McBride)", "what_happened": "The FTT held accommodation use was unlikely to be more than incidental to TAD services.", "why_it_matters": "Dolphin's high-water mark before HMRC's further appeals.", "legal_hook": "[2021] UKFTT 145 (TC)"},
                    {"id": "ut-dismisses-hmrc", "order": 6, "date": "2022-08-04", "date_label": "4 August 2022", "date_precision": "exact", "title": "Upper Tribunal dismisses HMRC appeal", "category": "decision", "actor": "UT (Falk J, Scott)", "what_happened": "The UT held the FTT had not misdirected itself on incidental use.", "why_it_matters": "Sent the substantive question to the Court of Appeal.", "legal_hook": "[2022] UKUT 212 (TCC)"},
                    {"id": "ca-hearing", "order": 7, "date": None, "date_label": "Court of Appeal, 2024", "date_precision": "year", "title": "Court of Appeal hears HMRC appeal", "category": "hearing", "actor": "Court of Appeal (Nugee, Newey, Peter Jackson LJJ)", "what_happened": "The court focused on whether the FTT asked the wrong question — relative importance rather than connection between uses.", "why_it_matters": "Ground 1 on the meaning of incidental was decisive.", "legal_hook": "Robson v Dixon"},
                    {"id": "appeal-allowed", "order": 8, "date": None, "date_label": "[2024] EWCA Civ 1", "date_precision": "unknown", "title": "Appeal allowed; hire cap applies", "category": "outcome", "actor": "Court of Appeal", "what_happened": "The court held accommodation of Dunbar workers was an independent significant use; the Borgsten was a relevant asset and the hire cap applied.", "why_it_matters": "Binding interpretation restoring HMRC assessments.", "legal_hook": "CTA 2010 section 356LA(3)"},
                ],
                "turning_points": [
                    {"stage_id": "ftt-victory", "label": "Tribunals treat accommodation as secondary", "impact": "Briefly accepted Dolphin's view that berths for Total staff were subordinate to TAD work."},
                    {"stage_id": "ca-hearing", "label": "Incidental means connected, not lesser", "impact": "Reframed the statutory test and undermined the FTT's reasoning."},
                    {"stage_id": "appeal-allowed", "label": "Hire cap restored", "impact": "Confirmed multi-million-pound tax liabilities for the accounting periods in issue."},
                ],
                "confidence": {"score": 0.88, "level": "high", "notes": "Key dates from 2011–2022 are stated in the judgment; Court of Appeal hand-down date not in source text."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/2.json",
        "judges": ["Sir Andrew McFarlane"],
        "enrichment": {
            "short_title": "Family court incidental orders under section 31E MFPA 1984",
            "area_of_law": ["Family law", "Family procedure", "Court powers", "Children law"],
            "statutes_considered": [
                {"title": "Matrimonial and Family Proceedings Act 1984", "provisions": ["section 31E", "section 31A", "section 31D", "section 38", "section 39", "Part 5"]},
                {"title": "Crime and Courts Act 2013", "provisions": ["Part 4A"]},
                {"title": "Children Act 1989", "provisions": ["section 8", "section 9", "section 22", "section 33", "section 37"]},
                {"title": "Family Court (Composition and Distribution of Business) Rules 2014", "provisions": ["Rules 14", "17", "Schedule 2"]},
            ],
            "key_facts": [
                "Care proceedings concerning brothers B (15) and A (12) ended with care orders and a family placement plan.",
                "The mother sought an injunction requiring the father to transfer Apple ID parental controls for the boys' phones.",
                "HHJ Gargan declined the injunction, holding as a circuit judge she lacked jurisdiction despite unanimous counsel submissions to the contrary.",
                "The Children's Guardian appealed; the Court of Appeal held any family court judge could make such incidental supplemental orders under section 31E(1)(a).",
            ],
            "procedural_posture": "Appeal by the Children's Guardian with permission of Peter Jackson LJ from a circuit judge's refusal to make an Apple ID injunction at the final care hearing.",
            "outcome": "Appeal allowed; matter remitted to HHJ Gargan to determine the mother's application on its merits.",
            "ratio": "Where properly issued family proceedings are before the family court, judges at any level may make incidental or supplemental orders that the High Court could make in equivalent proceedings, unless Schedule 2 to the 2014 Rules or Presidential Guidance reserves the remedy to High Court level. Section 31E(1)(a) MFPA 1984 is not limited to deputy High Court judges.",
            "legal_issues": [
                "Scope of section 31E(1)(a) MFPA 1984",
                "Whether circuit judges need section 9 authorisation for incidental High Court-type orders",
                "Interaction between the 2014 and 2018 Presidential Guidance and the statutory framework",
            ],
            "catchwords": ["family court powers", "section 31E", "incidental orders", "Apple parental controls", "care proceedings", "High Court inherent jurisdiction"],
            "index_terms": ["MFPA 1984", "Family Court Rules 2014", "Re K", "parental responsibility", "supplemental relief"],
            "linked_authorities": [
                "Re K (Maintenance Enforcement: Justices' Powers)",
                "CH v WH",
                "Re T (A Child)",
                "Manchester City Council v CP and Others",
            ],
            "confidence": {
                "score": 0.87,
                "level": "high",
                "notes": "Judgment is authored by the President as the judgment of the court; spurious Lord Chief Justice and Lord Chancellor metadata removed. Other panel members are not named in the source.",
            },
            "storyline": {
                "title": "Family court power to order Apple ID transfer in care proceedings",
                "summary": "After long-running care proceedings, a circuit judge refused an injunction over the father's control of the boys' iPhones because she doubted her jurisdiction. The Court of Appeal reaffirmed that section 31E MFPA 1984 lets any family court judge make incidental orders to give effect to substantive decisions, and remitted the application.",
                "span": {"start": "2021-08-01", "end": "2024-01-01", "label": "August 2021 – January 2024"},
                "parties": [
                    {"role": "appellant", "name": "Children's Guardian for B and A", "short_name": "Guardian"},
                    {"role": "claimant", "name": "Mother", "short_name": "Mother"},
                    {"role": "defendant", "name": "Father", "short_name": "Father"},
                    {"role": "authority", "name": "Local authority", "short_name": "LA"},
                    {"role": "court", "name": "Court of Appeal / Family Court", "short_name": "Court"},
                ],
                "stages": [
                    {"id": "fact-finding", "order": 1, "date": "2021-08-01", "date_label": "August 2021", "date_precision": "month", "title": "Fact-finding against father", "category": "hearing", "actor": "Family Court", "what_happened": "Strong findings of alienating and coercive behaviour led to a section 37 investigation and care proceedings.", "why_it_matters": "Background to interim removal and final care plans.", "legal_hook": "Children Act 1989 section 37"},
                    {"id": "interim-removal", "order": 2, "date": "2022-02-01", "date_label": "February 2022", "date_precision": "month", "title": "Boys removed under interim care orders", "category": "decision", "actor": "Family Court", "what_happened": "Children moved to a maternal family placement.", "why_it_matters": "Care orders followed at final hearing.", "legal_hook": "Children Act 1989"},
                    {"id": "final-hearing", "order": 3, "date": "2023-05-23", "date_label": "23–26 May 2023", "date_precision": "exact", "title": "Final care hearing", "category": "hearing", "actor": "HHJ Gargan", "what_happened": "Judge announced care orders with boys remaining in family placement; Apple ID injunction argued at end of hearing.", "why_it_matters": "Substantive orders made but phone control unresolved.", "legal_hook": None},
                    {"id": "jurisdiction-refused", "order": 4, "date": "2023-06-26", "date_label": "26 June 2023", "date_precision": "exact", "title": "Judge declines injunction for want of power", "category": "decision", "actor": "HHJ Gargan", "what_happened": "Despite support from five counsel, the judge held a circuit judge could not make the order, particularly involving Apple.", "why_it_matters": "Triggered the appeal on family court powers.", "legal_hook": "MFPA 1984 section 31E"},
                    {"id": "permission-granted", "order": 5, "date": None, "date_label": "Before Court of Appeal", "date_precision": "unknown", "title": "Peter Jackson LJ grants permission", "category": "procedural", "actor": "Peter Jackson LJ", "what_happened": "Permission to appeal on whether section 31E(1)(a) extends to circuit judges.", "why_it_matters": "Enabled authoritative guidance on family court jurisdiction.", "legal_hook": None},
                    {"id": "ca-guidance", "order": 6, "date": None, "date_label": "Court of Appeal judgment", "date_precision": "unknown", "title": "Court reaffirms wide family court powers", "category": "decision", "actor": "Sir Andrew McFarlane P", "what_happened": "The court summarised the statutory framework and held the judge had power unless Rules or Guidance specifically reserved the remedy.", "why_it_matters": "Practice guidance for allocation and incidental orders across the family court.", "legal_hook": "MFPA 1984 section 31E; 2018 Presidential Guidance para 15"},
                    {"id": "remitted", "order": 7, "date": None, "date_label": "Final order", "date_precision": "unknown", "title": "Appeal allowed; application remitted", "category": "outcome", "actor": "Court of Appeal", "what_happened": "Mother's Apple ID application remitted to HHJ Gargan for determination on up-to-date welfare grounds.", "why_it_matters": "Jurisdiction confirmed but merits left to first-instance judge.", "legal_hook": None},
                ],
                "turning_points": [
                    {"stage_id": "jurisdiction-refused", "label": "Circuit judge doubts section 31E reach", "impact": "Created apparent barrier to practical welfare orders in ongoing care cases."},
                    {"stage_id": "ca-guidance", "label": "Four-question test for incidental orders", "impact": "Clarified when any family court judge may make supplemental relief."},
                ],
                "confidence": {"score": 0.84, "level": "high", "notes": "May–June 2023 dates explicit; appeal hand-down date not stated in source."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/3.json",
        "judges": ["Lord Justice Peter Jackson", "Lord Justice Dingemans", "Lord Justice Lewis"],
        "enrichment": {
            "short_title": "Best interests travel to Afghanistan for incapacitated adult",
            "area_of_law": ["Court of Protection", "Mental capacity", "Human rights", "Public law"],
            "statutes_considered": [
                {"title": "Mental Capacity Act 2005", "provisions": ["section 1", "section 4"]},
                {"title": "Family Law Act 1996", "provisions": ["Part 4A"]},
            ],
            "key_facts": [
                "J, a young man with severe learning difficulties, lives with his Afghan refugee family in Luton.",
                "An interim FMPO and port alert prevented travel after capacity assessments found J lacked capacity to marry and engage in sexual relations.",
                "In July 2023 the family sought permission for J to travel to Afghanistan for five weeks; Roberts J refused on FCDO safety grounds.",
                "The Official Solicitor appealed; the family supported the appeal but the local authority opposed it.",
            ],
            "procedural_posture": "Appeal by the Official Solicitor as litigation friend with permission on Ground 1 from Peter Jackson LJ.",
            "outcome": "Appeal dismissed; Roberts J's best interests refusal upheld as open on the evidence.",
            "ratio": "A best interests decision under section 4 MCA 2005 may lawfully give substantial weight to FCDO travel advice where risks to life, limb and liberty are real, provided the judge conducts the full section 4 evaluative exercise including wishes, values and family views. Generic FCDO guidance is influential but need not be treated as automatically decisive.",
            "legal_issues": [
                "Weight of FCDO travel advice in section 4 MCA 2005 assessments",
                "Whether the judge failed to consider J's wishes and feelings",
                "Article 14 discrimination where a capacitous person could choose to ignore FCDO advice",
            ],
            "catchwords": ["best interests", "Mental Capacity Act", "Afghanistan travel", "FCDO advice", "forced marriage protection", "Article 8"],
            "index_terms": ["Court of Protection", "Official Solicitor", "port alert", "learning disability", "family holiday"],
            "linked_authorities": [
                "Aintree University Hospitals NHS Foundation Trust v James",
                "An NHS Trust v P",
                "Re UR",
            ],
            "confidence": {
                "score": 0.9,
                "level": "high",
                "notes": "Roberts J removed from appeal panel metadata; Peter Jackson, Dingemans and Lewis LJJ named at judgment end.",
            },
            "storyline": {
                "title": "Court blocks incapacitated man's Afghanistan holiday on FCDO risk",
                "summary": "A Luton family wanted their learning-disabled son to visit Afghanistan with them, but the Court of Protection refused after weighing FCDO advice on extreme security risks. The Court of Appeal dismissed the Official Solicitor's challenge, holding the judge had properly balanced section 4 MCA 2005 factors.",
                "span": {"start": "2022-01-01", "end": "2024-01-01", "label": "January 2022 – January 2024"},
                "parties": [
                    {"role": "appellant", "name": "J (by Official Solicitor)", "short_name": "J"},
                    {"role": "defendant", "name": "Luton Borough Council", "short_name": "Council"},
                    {"role": "family", "name": "J's parents and sister", "short_name": "Family"},
                    {"role": "court", "name": "Court of Appeal / Court of Protection", "short_name": "Court"},
                ],
                "stages": [
                    {"id": "capacity-assessment", "order": 1, "date": "2022-08-02", "date_label": "2 August 2022", "date_precision": "exact", "title": "Capacity assessment on marriage and travel", "category": "institutional", "actor": "Local authority", "what_happened": "J assessed as lacking capacity to marry and engage in sexual relations as family planned Afghanistan trip.", "why_it_matters": "Triggered FMPO and port alert.", "legal_hook": "MCA 2005"},
                    {"id": "fmpo", "order": 2, "date": "2022-08-01", "date_label": "August 2022", "date_precision": "month", "title": "Interim FMPO and port alert", "category": "decision", "actor": "Family Court", "what_happened": "Forced Marriage Protection Order granted; family prevented from travelling.", "why_it_matters": "Parallel CoP and family proceedings began.", "legal_hook": "Family Law Act 1996 Part 4A"},
                    {"id": "partial-discharge", "order": 3, "date": "2023-03-17", "date_label": "17 March 2023", "date_precision": "exact", "title": "FMPO varied for other family members", "category": "decision", "actor": "Court", "what_happened": "Port alert discharged for parents and sister; FMPO remained for J pending travel capacity assessment.", "why_it_matters": "Family renewed travel application for J.", "legal_hook": None},
                    {"id": "travel-application", "order": 4, "date": "2023-07-14", "date_label": "14 July 2023", "date_precision": "exact", "title": "Oral application for Afghanistan trip", "category": "procedural", "actor": "Family", "what_happened": "Family applied for J to travel 31 July 2023 for five weeks; urgent hearing listed 26 July.", "why_it_matters": "Core best interests decision point.", "legal_hook": None},
                    {"id": "roberts-refusal", "order": 5, "date": "2023-07-26", "date_label": "26 July 2023", "date_precision": "exact", "title": "Roberts J refuses travel", "category": "decision", "actor": "Mrs Justice Roberts", "what_happened": "Judge weighed FCDO advice, family mitigation and section 4 factors; refused travel as risks too grave.", "why_it_matters": "Decision under appeal.", "legal_hook": "MCA 2005 section 4"},
                    {"id": "permission", "order": 6, "date": "2023-10-12", "date_label": "12 October 2023", "date_precision": "exact", "title": "Permission to appeal granted", "category": "procedural", "actor": "Peter Jackson LJ", "what_happened": "Ground 1 arguable on weight given to FCDO guidance versus individual factors.", "why_it_matters": "Enabled Court of Appeal review.", "legal_hook": None},
                    {"id": "airport-incident", "order": 7, "date": None, "date_label": "After 26 July 2023", "date_precision": "approximate", "title": "Family detained at airport", "category": "factual", "actor": "Border authorities", "what_happened": "Out-of-date port alert caused family members to be arrested and separated for hours when travelling without J.", "why_it_matters": "Highlighted systemic port-alert error; referred to Family Division President.", "legal_hook": None},
                    {"id": "appeal-dismissed", "order": 8, "date": None, "date_label": "[2024] EWCA Civ 3", "date_precision": "unknown", "title": "Appeal dismissed", "category": "outcome", "actor": "Court of Appeal", "what_happened": "Court held judge properly balanced section 4 factors; FCDO risks lawfully tipped balance.", "why_it_matters": "Travel remains subject to future best interests review.", "legal_hook": "Aintree v James"},
                ],
                "turning_points": [
                    {"stage_id": "roberts-refusal", "label": "FCDO risks outweigh family benefits", "impact": "Blocked imminent five-week Afghanistan trip."},
                    {"stage_id": "appeal-dismissed", "label": "Evaluative judgment stands", "impact": "Confirmed heavy but lawful weight for official travel advice in CoP cases."},
                ],
                "confidence": {"score": 0.86, "level": "high", "notes": "July–October 2023 dates explicit; hand-down date not in source."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/4.json",
        "judges": ["Lady Justice Elisabeth Laing", "Lady Justice Andrews", "Lord Justice Phillips"],
        "enrichment": {
            "short_title": "HCEO liability for enforcement agent fees under writ of control",
            "area_of_law": ["Civil procedure", "Enforcement of judgments", "High Court enforcement", "Statutory interpretation"],
            "statutes_considered": [
                {"title": "Tribunals, Courts and Enforcement Act 2007", "provisions": ["section 62", "section 63", "Schedule 12", "paragraph 66"]},
                {"title": "Courts Act 2003", "provisions": ["Schedule 7", "section 99"]},
                {"title": "Taking Control of Goods (Fees) Regulations 2014", "provisions": ["regulation 4", "regulation 16"]},
                {"title": "High Court Enforcement Officers Regulations 2004", "provisions": ["regulation 8", "regulation 13"]},
            ],
            "key_facts": [
                "Mr Bone obtained a writ of control directed to HCEO Mr Williamson after judgment for £24,000.",
                "Mr Williamson engaged HCEA Mr Brown of DCBL to enforce; fees of £5,703.60 were charged on a first visit.",
                "Mr Bone disputed fees under regulation 16 against Mr Williamson; Master Sullivan held the HCEO was not the correct defendant.",
                "The HCEOs' Association intervened supporting Mr Bone; the Court of Appeal held the HCEO is the proper respondent to fee disputes.",
            ],
            "procedural_posture": "Appeal with permission of Warby LJ from Lambert J's dismissal of Mr Bone's appeal from Master Sullivan.",
            "outcome": "Appeal allowed; HCEO is proper defendant to regulation 16 fee disputes and related party under Schedule 12 paragraph 66.",
            "ratio": "Under the Schedule 12 enforcement scheme, the HCEO on whom the writ is directed remains legally responsible for enforcement: proceeds and fee entitlements flow through the HCEO's nominated account, and a debtor may properly bring a regulation 16 fees dispute against the HCEO rather than only against the certificated enforcement agent who acted on the ground.",
            "legal_issues": [
                "Whether Schedule 12 and the Fees Regulations form a self-contained scheme excluding HCEO liability",
                "Who is the correct defendant to a regulation 16 fees dispute",
                "Whether section 63(2)(c) TCEA exempts HCEOs from needing HCEA certification",
            ],
            "catchwords": ["High Court enforcement officer", "enforcement agent", "writ of control", "regulation 16", "fee dispute", "Schedule 12"],
            "index_terms": ["DCBL", "bareboat charter analogy rejected", "proceeds of enforcement", "related party"],
            "linked_authorities": ["Court Enforcement Services Ltd v Marston Legal Services Ltd", "Just Digital Marketplace v HCEOA"],
            "confidence": {
                "score": 0.89,
                "level": "high",
                "notes": "Spurious Lord Chancellor and Lord Leggatt metadata removed; Laing, Andrews and Phillips LJJ identified in judgment.",
            },
            "storyline": {
                "title": "Debtor's fee fight pins liability on High Court enforcement officer",
                "summary": "After a writ of control, certificated agent fees were challenged but the HCEO argued he was the wrong defendant. The Court of Appeal held the statutory scheme makes the HCEO — not the roaming enforcement agent — the proper respondent to fee disputes and keeper of enforcement proceeds.",
                "span": {"start": "2019-09-17", "end": "2024-01-01", "label": "September 2019 – January 2024"},
                "parties": [
                    {"role": "appellant", "name": "Trevor Bone", "short_name": "Bone"},
                    {"role": "respondent", "name": "Simon Williamson (HCEO)", "short_name": "Williamson"},
                    {"role": "agent", "name": "Mr Brown / DCBL", "short_name": "Brown"},
                    {"role": "intervenor", "name": "High Court Enforcement Officers' Association", "short_name": "HCEOA"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "judgment-debt", "order": 1, "date": None, "date_label": "Before September 2019", "date_precision": "unknown", "title": "Judgment for £24,000", "category": "decision", "actor": "High Court", "what_happened": "Claimants obtained judgment against Mr Bone.", "why_it_matters": "Basis for enforcement.", "legal_hook": None},
                    {"id": "writ-issued", "order": 2, "date": "2019-09-17", "date_label": "17 September 2019", "date_precision": "exact", "title": "Writ of control directed to Williamson", "category": "procedural", "actor": "High Court", "what_happened": "Writ commanded Williamson to seize goods and raise sums including entitled fees.", "why_it_matters": "Williamson remained officer of record throughout.", "legal_hook": "Courts Act 2003 Schedule 7"},
                    {"id": "first-enforcement", "order": 3, "date": "2019-10-03", "date_label": "3 October 2019", "date_precision": "exact", "title": "Brown visits; fees charged", "category": "factual", "actor": "Mr Brown (HCEA)", "what_happened": "First enforcement visit generated DCBL fees of £5,703.60.", "why_it_matters": "Fees dispute arose.", "legal_hook": "Fees Regulations 2014"},
                    {"id": "stay-breach", "order": 4, "date": "2020-01-10", "date_label": "10 January 2020", "date_precision": "exact", "title": "Enforcement during stay of execution", "category": "factual", "actor": "Brown / Williamson", "what_happened": "Second visit occurred despite Master Davison's stay order; damages claim later dismissed.", "why_it_matters": "Added complexity and costs.", "legal_hook": None},
                    {"id": "fee-application", "order": 5, "date": "2020-09-18", "date_label": "18 September 2020", "date_precision": "exact", "title": "Bone applies under regulation 16", "category": "procedural", "actor": "Mr Bone", "what_happened": "Application for fee assessment and stay brought against Williamson only.", "why_it_matters": "Correct defendant issue central to appeal.", "legal_hook": "CPR Part 84.16"},
                    {"id": "master-wrong-defendant", "order": 6, "date": "2021-02-10", "date_label": "10 February 2021", "date_precision": "exact", "title": "Master Sullivan: HCEO not correct defendant", "category": "decision", "actor": "Master Sullivan", "what_happened": "Master held fees belonged to HCEA; awarded Williamson costs of fee dispute.", "why_it_matters": "First-instance rejection of Bone's approach.", "legal_hook": "Fees Regulations regulation 4"},
                    {"id": "lambert-dismissal", "order": 7, "date": None, "date_label": "Before appeal", "date_precision": "unknown", "title": "Lambert J dismisses appeal", "category": "decision", "actor": "Lambert J", "what_happened": "Judge upheld self-contained scheme analysis favouring HCEA as fee defendant.", "why_it_matters": "Sent issue to Court of Appeal.", "legal_hook": None},
                    {"id": "ca-allowed", "order": 8, "date": None, "date_label": "[2024] EWCA Civ 4", "date_precision": "unknown", "title": "Appeal allowed on fee defendant point", "category": "outcome", "actor": "Court of Appeal (Laing, Andrews, Phillips LJJ)", "what_happened": "HCEO is proper regulation 16 respondent; costs reallocated.", "why_it_matters": "Protects debtors and aligns with HCEOA best practice.", "legal_hook": "Schedule 12 paragraph 66"},
                ],
                "turning_points": [
                    {"stage_id": "master-wrong-defendant", "label": "Fees treated as agent's property", "impact": "Left debtor pursuing wrong party while HCEO costs mounted."},
                    {"stage_id": "ca-allowed", "label": "HCEO remains principal", "impact": "Restored debtor protection under writ-directed enforcement scheme."},
                ],
                "confidence": {"score": 0.85, "level": "high", "notes": "2019–2021 procedural dates from judgment; appeal date not stated."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/5.json",
        "judges": ["Sir Geoffrey Vos", "Lord Justice Coulson", "Lord Justice Phillips"],
        "enrichment": {
            "short_title": "Non-assignment clause and insurance subrogation by operation of law",
            "area_of_law": ["Contract law", "Arbitration", "Insurance law", "Commercial contracts"],
            "statutes_considered": [
                {"title": "Arbitration Act 1996", "provisions": ["section 67"]},
                {"title": "Japanese Insurance Act 2008", "provisions": ["article 25", "article 35"]},
                {"title": "Contracts (Rights of Third Parties) Act 1999", "provisions": []},
            ],
            "key_facts": [
                "Dassault sold two Falcon aircraft to MBA under an English-law contract with a non-assignment clause in article 15.",
                "MBA insured late-delivery liability with MSI; MSI paid JPY 1.8 billion to the Japanese Coast Guard after late delivery.",
                "Under Japanese Insurance Act article 25, MBA's claims against Dassault transferred to MSI by operation of law.",
                "Arbitrators held article 15 did not block the transfer; Cockerill J allowed a section 67 appeal but the Court of Appeal restored the award.",
            ],
            "procedural_posture": "MSI appeal under section 67 Arbitration Act 1996 from Cockerill J's setting aside of ICC arbitral award on jurisdiction.",
            "outcome": "Appeal allowed; arbitral award reinstated; transfer by operation of law not an assignment by a party under article 15.",
            "ratio": "Article 15's prohibition on assignment 'by any Party' does not catch transfers effected by operation of law under Japanese Insurance Act article 25. The words 'by any Party' require the transfer to be made by a contracting party, not merely caused by their voluntary insurance arrangements.",
            "legal_issues": [
                "Construction of non-assignment clause article 15",
                "Distinction between voluntary assignment and subrogation by operation of law",
                "Whether old insolvency authorities on voluntary/involuntary transfers apply",
            ],
            "catchwords": ["non-assignment clause", "subrogation", "operation of law", "section 67", "aircraft sale contract", "insurance payout"],
            "index_terms": ["Dassault Aviation", "Mitsui Sumitomo Insurance", "MBA", "ICC arbitration", "article 15"],
            "linked_authorities": ["Rainy Sky SA v Kookmin Bank", "Wood v Capita Insurance Services Ltd", "Cohen v Popular Restaurants"],
            "confidence": {
                "score": 0.92,
                "level": "high",
                "notes": "Spurious deceased Law Lords removed from metadata; Vos MR, Coulson and Phillips LJJ identified in judgment.",
            },
            "storyline": {
                "title": "Insurer's subrogated claim survives aircraft sale non-assignment clause",
                "summary": "After MSI paid liquidated damages for late delivery of Dassault aircraft, it pursued Dassault in ICC arbitration relying on Japanese-law subrogation. Dassault argued article 15 blocked the claim, but the Court of Appeal held a transfer by operation of law is not an assignment by any party.",
                "span": {"start": "2015-03-06", "end": "2024-01-01", "label": "March 2015 – January 2024"},
                "parties": [
                    {"role": "appellant", "name": "Mitsui Sumitomo Insurance Co Ltd", "short_name": "MSI"},
                    {"role": "respondent", "name": "Dassault Aviation SA", "short_name": "Dassault"},
                    {"role": "insured", "name": "Mitsui Bussan Aerospace Co Ltd", "short_name": "MBA"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "sale-contract", "order": 1, "date": "2015-03-06", "date_label": "6 March 2015", "date_precision": "exact", "title": "Aircraft sale contract signed", "category": "factual", "actor": "Dassault / MBA", "what_happened": "English-law sale contract included article 15 non-assignment clause.", "why_it_matters": "Clause central to jurisdiction dispute.", "legal_hook": "Article 15"},
                    {"id": "late-delivery", "order": 2, "date": None, "date_label": "After 2015", "date_precision": "unknown", "title": "Aircraft delivered late to Coast Guard", "category": "factual", "actor": "MBA / Dassault", "what_happened": "Late delivery triggered liquidated damages under Japanese sub-sale.", "why_it_matters": "Generated insurable loss.", "legal_hook": None},
                    {"id": "insurance-payout", "order": 3, "date": "2020-05-11", "date_label": "11 May 2020", "date_precision": "exact", "title": "MSI pays JPY 1.8 billion", "category": "factual", "actor": "MSI", "what_happened": "Insurer indemnified MBA; claims transferred by article 25 Insurance Act.", "why_it_matters": "Created MSI's direct claim against Dassault.", "legal_hook": "Japanese Insurance Act article 25"},
                    {"id": "arbitration", "order": 4, "date": "2021-01-01", "date_label": "Mid-2021", "date_precision": "approximate", "title": "ICC arbitration commenced", "category": "procedural", "actor": "MSI", "what_happened": "MSI pursued Dassault; tribunal upheld jurisdiction 2–1 on article 15 construction.", "why_it_matters": "Majority aligned with MSI's core proposition.", "legal_hook": "Arbitration Act 1996"},
                    {"id": "s67-appeal", "order": 5, "date": None, "date_label": "Before Court of Appeal", "date_precision": "unknown", "title": "Cockerill J allows section 67 appeal", "category": "decision", "actor": "Cockerill J", "what_happened": "Judge held article 15 caught voluntary insurance-driven transfer; award set aside.", "why_it_matters": "Temporary loss of tribunal jurisdiction.", "legal_hook": "Section 67"},
                    {"id": "ca-restores-award", "order": 6, "date": None, "date_label": "[2024] EWCA Civ 5", "date_precision": "unknown", "title": "Court of Appeal reinstates award", "category": "outcome", "actor": "Court of Appeal (Vos MR, Coulson, Phillips LJJ)", "what_happened": "Held article 15 plain meaning excludes operation-of-law transfers; appeal allowed.", "why_it_matters": "MSI may proceed against Dassault in arbitration.", "legal_hook": "Article 15 construction"},
                ],
                "turning_points": [
                    {"stage_id": "insurance-payout", "label": "Subrogation by operation of law", "impact": "Transferred MBA's contract claims to MSI without contractual assignment."},
                    {"stage_id": "ca-restores-award", "label": "Non-assignment clause narrowly construed", "impact": "Preserved insurer's direct arbitral route against manufacturer."},
                ],
                "confidence": {"score": 0.87, "level": "high", "notes": "2015 contract and 2020 payout dates explicit; arbitration start approximate."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/7.json",
        "judges": ["Lady Justice Andrews", "Lady Justice Elisabeth Laing", "Lord Justice Phillips"],
        "enrichment": {
            "short_title": "Solicitors PII condonation and aggregation after dishonest partner",
            "area_of_law": ["Professional indemnity insurance", "Solicitors regulation", "Insurance construction", "Fraud"],
            "statutes_considered": [
                {"title": "Third Party (Rights Against Insurers) Act 2010", "provisions": ["section 1"]},
                {"title": "Solicitors Act 1974", "provisions": ["section 37"]},
                {"title": "SRA Indemnity Insurance Rules 2013", "provisions": ["Appendix 1 MTC", "clause 2.5", "clause 2.8"]},
            ],
            "key_facts": [
                "Clients of dishonest solicitor Stephen Jones claimed on Axis PII after Jirehouse entities became insolvent.",
                "Claims related to misappropriation of Taymouth Castle purchase funds and a Dragonfly loan charge.",
                "Knowles J held co-director Prentice did not condone Jones's dishonesty and claims were not aggregatable.",
                "Axis appealed both fact findings with Knowles J's permission; the Court of Appeal dismissed the appeal.",
            ],
            "procedural_posture": "Appeal with permission of Knowles J on condonation and aggregation issues from a trial of preliminary coverage issues.",
            "outcome": "Appeal dismissed on both grounds; exclusion clause 2.8 and aggregation clause 5.2( e) construed against insurer.",
            "ratio": "Condonation under clause 2.8 requires knowledge and acceptance of the specific dishonest conduct giving rise to the claim, not merely blind-eye suspicion of a pattern. The Surplus Funds and Dragonfly claims were not 'similar acts or omissions in a series of related matters or transactions' for aggregation under AIG v Woodman.",
            "legal_issues": [
                "Whether Prentice condoned Jones's dishonesty for clause 2.8 purposes",
                "Meaning of similar acts in related transactions for MTC aggregation",
                "Appellate review of trial judge fact-findings on condonation",
            ],
            "catchwords": ["professional indemnity", "condonation", "aggregation", "solicitors fraud", "Third Party (Rights Against Insurers) Act", "building scheme rejected"],
            "index_terms": ["Jirehouse Partners", "Stephen Jones", "Taymouth Castle", "Dragonfly loan", "Axis Specialty Europe"],
            "linked_authorities": [
                "AIG Europe Ltd v Woodman",
                "Impact Funding Solutions Ltd v Barrington Support Services Ltd",
                "Group Seven Ltd v Nasir",
                "Scott v Copenhagen Reinsurance Co",
            ],
            "confidence": {
                "score": 0.88,
                "level": "high",
                "notes": "Spurious Supreme Court judges removed; Andrews LJ gave lead judgment with Laing and Phillips LJJ agreeing.",
            },
            "storyline": {
                "title": "Insurer fails to exclude cover after solicitor's castle fraud",
                "summary": "Axis sought to avoid paying PII claims arising from Stephen Jones's theft of client funds for Taymouth Castle and a clandestine Dragonfly loan. The Court of Appeal upheld Knowles J's findings that co-director Prentice did not condone the fraud and the two claims could not be aggregated.",
                "span": {"start": "2016-01-01", "end": "2024-01-01", "label": "2016 – January 2024"},
                "parties": [
                    {"role": "appellant", "name": "Axis Speciality Europe SE", "short_name": "Axis"},
                    {"role": "claimants", "name": "Discovery Land Company and related claimants", "short_name": "DLC"},
                    {"role": "insured", "name": "Jirehouse Partners LLP and related entities", "short_name": "Jirehouse"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "client-funds-received", "order": 1, "date": "2018-04-16", "date_label": "16 April 2018", "date_precision": "exact", "title": "US$14m sent for castle purchase", "category": "factual", "actor": "DLC / Jirehouse", "what_happened": "Purchase funds transferred to Jirehouse client account then misappropriated by Jones.", "why_it_matters": "First major theft underpinning Surplus Funds claim.", "legal_hook": None},
                    {"id": "castle-exchange", "order": 2, "date": "2018-05-29", "date_label": "29 May 2018", "date_precision": "exact", "title": "Contracts exchanged on Taymouth Castle", "category": "factual", "actor": "Jones / clients", "what_happened": "Castle purchase proceeded while Jones syphoned further funds.", "why_it_matters": "Context for later Dragonfly loan fraud.", "legal_hook": None},
                    {"id": "dragonfly-loan", "order": 3, "date": "2019-01-21", "date_label": "21 January 2019", "date_precision": "exact", "title": "Clandestine Dragonfly charge", "category": "factual", "actor": "Stephen Jones", "what_happened": "Jones charged castle via RTC without client knowledge; proceeds misappropriated.", "why_it_matters": "Second claim Axis argued should aggregate with first.", "legal_hook": None},
                    {"id": "prentice-resigns", "order": 4, "date": "2019-03-15", "date_label": "15 March 2019", "date_precision": "exact", "title": "Prentice resigns after confession", "category": "factual", "actor": "Vieoence Prentice", "what_happened": "Jones admitted paying away Dragonfly proceeds; Prentice resigned same day.", "why_it_matters": "Central to condonation analysis.", "legal_hook": None},
                    {"id": "default-judgments", "order": 5, "date": "2019-07-30", "date_label": "30 July 2019", "date_precision": "exact", "title": "Default judgments against Jirehouse", "category": "decision", "actor": "High Court", "what_happened": "Claimants obtained judgment; entities insolvent triggering TPRAI claims.", "why_it_matters": "Moved dispute to insurer.", "legal_hook": "Third Party (Rights Against Insurers) Act 2010"},
                    {"id": "trial-findings", "order": 6, "date": None, "date_label": "Knowles J trial", "date_precision": "unknown", "title": "No condonation; no aggregation", "category": "decision", "actor": "Knowles J", "what_happened": "Judge rejected blind-eye condonation and held claims not similar related transactions.", "why_it_matters": "Axis liable subject to £250k excess per claim.", "legal_hook": "Clause 2.8; clause 5.2(e)"},
                    {"id": "appeal-dismissed", "order": 7, "date": None, "date_label": "[2024] EWCA Civ 7", "date_precision": "unknown", "title": "Court of Appeal dismisses appeal", "category": "outcome", "actor": "Court of Appeal (Andrews, Laing, Phillips LJJ)", "what_happened": "Fact findings not plainly wrong; Dragonfly and Surplus Funds claims distinct for aggregation.", "why_it_matters": "Maintains separate £3m limits per claim.", "legal_hook": "AIG v Woodman"},
                ],
                "turning_points": [
                    {"stage_id": "trial-findings", "label": "Prentice not a condoner", "impact": "Clause 2.8 exclusion failed despite adverse credibility findings."},
                    {"stage_id": "appeal-dismissed", "label": "Two frauds, two claims", "impact": "Aggregation cannot collapse limits for structurally different dishonest acts."},
                ],
                "confidence": {"score": 0.84, "level": "high", "notes": "2018–2019 event dates from judgment; trial and appeal dates not stated."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/9.json",
        "judges": ["Lord Justice Nugee", "Lord Justice Snowden", "Sir Geoffrey Vos"],
        "enrichment": {
            "short_title": "Representative action over undisclosed patent renewal commissions",
            "area_of_law": ["Civil procedure", "Representative actions", "Fiduciary duties", "Commercial litigation"],
            "statutes_considered": [
                {"title": "Civil Procedure Rules 1998", "provisions": ["Part 19", "rule 19.8"]},
                {"title": "Limitation Act 1980", "provisions": ["section 32"]},
            ],
            "key_facts": [
                "Marks & Clerk LLP referred clients to CPA Global for IP renewal fees and received undisclosed commissions via Long Acre Renewals.",
                "Commission Recovery Ltd (CRL) assigned Bambach Europe's claim and sued as representative of thousands of affected clients.",
                "Knowles J dismissed M&C's application to strike out and to bar representative status under CPR 19.8(2).",
                "The Court of Appeal upheld representative proceedings on CRL's core proposition liability issue.",
            ],
            "procedural_posture": "Appeal with permission of Males LJ from Knowles J's refusal to strike out or direct that CRL may not act as representative.",
            "outcome": "Appeal dismissed; representative action permitted to proceed on common core proposition issue under CPR 19.8.",
            "ratio": "Members of a class have the same interest under CPR 19.8 where a common legal issue exists and there is no conflict between class members. A bifurcated representative stage may resolve whether standard terms plus commission payment suffice for liability, leaving disclosure, limitation and quantum for later individual stages.",
            "legal_issues": [
                "Whether CRL's core proposition is a common issue for representative proceedings",
                "Whether class definition presupposes liability (Emerald Supplies objection)",
                "Discretion under CPR 19.8(2) where monetary relief requires later opt-in claimants",
            ],
            "catchwords": ["representative action", "CPR 19.8", "secret commission", "fiduciary duty", "bribery", "Lloyd v Google", "bifurcated process"],
            "index_terms": ["Marks & Clerk", "Commission Recovery Ltd", "CPA Global", "Long Acre Renewals", "patent renewals"],
            "linked_authorities": [
                "Lloyd v Google LLC",
                "Emerald Supplies Ltd v British Airways plc",
                "Prudential Assurance Co Ltd v Newman Industries Ltd",
                "Hurstanger Ltd v Wilson",
            ],
            "confidence": {
                "score": 0.91,
                "level": "high",
                "notes": "Spurious Supreme Court judges removed; Nugee LJ gave lead judgment with Snowden LJ and Vos MR agreeing.",
            },
            "storyline": {
                "title": "Patent firm clients pursue class action over secret renewal commissions",
                "summary": "Commission Recovery Ltd sought to represent thousands of Marks & Clerk clients alleging undisclosed CPA renewal commissions breached fiduciary duties. The Court of Appeal allowed the representative claim to proceed on a common core proposition, rejecting an attempt to stop the litigation at the threshold.",
                "span": {"start": "2006-02-01", "end": "2024-01-01", "label": "February 2006 – January 2024"},
                "parties": [
                    {"role": "claimant", "name": "Commission Recovery Ltd", "short_name": "CRL"},
                    {"role": "defendants", "name": "Marks & Clerk LLP and Long Acre Renewals", "short_name": "M&C"},
                    {"role": "assignor", "name": "Bambach Saddle Seat (Europe) Ltd", "short_name": "Bambach"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "commission-scheme", "order": 1, "date": "2006-02-01", "date_label": "From February 2006", "date_precision": "month", "title": "CPA pays commissions to LAR", "category": "factual", "actor": "CPA / LAR", "what_happened": "Renewals provider paid commissions on client referrals without routine client disclosure.", "why_it_matters": "Foundation of fiduciary and bribery claims.", "legal_hook": None},
                    {"id": "llp-transfer", "order": 2, "date": "2009-03-14", "date_label": "14 March 2009", "date_precision": "exact", "title": "M&C business transfers to LLP", "category": "institutional", "actor": "Marks & Clerk", "what_happened": "Partnership became LLP; standard terms authorised passing client details to CPA.", "why_it_matters": "Defined class membership from March 2009.", "legal_hook": None},
                    {"id": "crl-incorporated", "order": 3, "date": "2019-01-01", "date_label": "2019", "date_precision": "year", "title": "CRL incorporated as claims vehicle", "category": "procedural", "actor": "CRL", "what_happened": "Vehicle created; took assignment from Bambach Europe.", "why_it_matters": "Enabled funded collective litigation.", "legal_hook": None},
                    {"id": "claim-issued", "order": 4, "date": "2021-04-12", "date_label": "12 April 2021", "date_precision": "exact", "title": "Representative claim issued", "category": "procedural", "actor": "CRL", "what_happened": "Claim Form issued suing as assignee and representative of affected clients.", "why_it_matters": "Triggered strike-out and representative status applications.", "legal_hook": "CPR 19.8"},
                    {"id": "defendants-application", "order": 5, "date": "2021-06-30", "date_label": "30 June 2021", "date_precision": "exact", "title": "M&C apply to bar representative status", "category": "procedural", "actor": "M&C LLP / LAR", "what_happened": "Application under CPR 19.8(2) and strike-out of representative pleading.", "why_it_matters": "Core procedural battle on appeal.", "legal_hook": "CPR 19.8(2)"},
                    {"id": "knowles-dismisses", "order": 6, "date": "2023-02-24", "date_label": "24 February 2023", "date_precision": "exact", "title": "Knowles J allows representative claim", "category": "decision", "actor": "Robin Knowles J", "what_happened": "Judge held same interest satisfied and discretion favoured representative proceedings.", "why_it_matters": "First-instance green light for class litigation.", "legal_hook": "Lloyd v Google"},
                    {"id": "permission", "order": 7, "date": "2023-05-25", "date_label": "25 May 2023", "date_precision": "exact", "title": "Males LJ grants permission to appeal", "category": "procedural", "actor": "Males LJ", "what_happened": "Appeal permitted on representative status and pleading adequacy.", "why_it_matters": "Enabled Court of Appeal review.", "legal_hook": None},
                    {"id": "main-trial-issues", "order": 8, "date": "2023-11-14", "date_label": "14 November 2023", "date_precision": "exact", "title": "Judge approves main trial issue list", "category": "procedural", "actor": "Knowles J", "what_happened": "Core proposition issue listed for representative main trial; CMC scheduled.", "why_it_matters": "Shows litigation progressing pending appeal.", "legal_hook": None},
                    {"id": "appeal-dismissed", "order": 9, "date": None, "date_label": "[2024] EWCA Civ 9", "date_precision": "unknown", "title": "Court of Appeal dismisses appeal", "category": "outcome", "actor": "Court of Appeal (Nugee, Snowden LJJ; Vos MR)", "what_happened": "Representative action upheld on common core proposition; discretion not misapplied.", "why_it_matters": "Collective commission litigation may proceed to main trial.", "legal_hook": "CPR 19.8"},
                ],
                "turning_points": [
                    {"stage_id": "knowles-dismisses", "label": "Representative status preserved", "impact": "Avoided forcing thousands of individual claims."},
                    {"stage_id": "appeal-dismissed", "label": "Bifurcated class route confirmed", "impact": "Common liability principles may be tried before individual quantum."},
                ],
                "confidence": {"score": 0.88, "level": "high", "notes": "April 2021–November 2023 procedural dates explicit; hand-down date not in source."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/10.json",
        "judges": ["Lord Justice Males", "Lord Justice Newey", "Sir Julian Flaux"],
        "enrichment": {
            "short_title": "COVID business interruption aggregation and prevention of access cover",
            "area_of_law": ["Insurance law", "Business interruption", "Policy construction", "Commercial insurance"],
            "statutes_considered": [
                {"title": "Health Protection (Coronavirus, Business Closure) (England) Regulations 2020", "provisions": []},
            ],
            "key_facts": [
                "Various Eateries Trading Ltd (Strada/Coppa Club restaurants) claimed over £16m BI loss from COVID-19 under Marsh Resilience Form policy.",
                "Allianz paid £2.5m arguing losses connected to single Wuhan outbreak; Butcher J found government March 2020 actions were relevant occurrences.",
                "VE appealed per-location aggregation; Allianz appealed remoteness and prevention-of-access temporal scope.",
                "Court of Appeal dismissed both appeals; Wuhan and UK introduction too remote; aggregation not per insured location.",
            ],
            "procedural_posture": "Cross-appeals with permission of Butcher J from preliminary issues trial on Marsh Resilience Form BI cover.",
            "outcome": "Both appeals dismissed; Wuhan occurrence too remote; aggregation not per location; prevention of access covers loss beyond policy period if event starts within it.",
            "ratio": "Under a weak 'in connection with a single occurrence' clause, remoteness applies flexibly but Wuhan initial infections remain too remote from restaurant closure losses; meaningful explanation is UK government response. SBIL aggregation applies business-wide, not per Insured Location. Enforced closure or prevention of access during the Period of Insurance triggers indemnity for resulting interruption even if closure continues after expiry.",
            "legal_issues": [
                "Remoteness of Wuhan initial infection as aggregating occurrence",
                "Whether aggregation operates per Insured Location",
                "Whether prevention of access cover limited to losses within Period of Insurance",
            ],
            "catchwords": ["business interruption", "COVID-19", "aggregation clause", "single occurrence", "prevention of access", "Marsh Resilience Form"],
            "index_terms": ["Various Eateries", "Allianz", "Butcher J", "FCA v Arch", "Scott v Copenhagen Re"],
            "linked_authorities": [
                "Financial Conduct Authority v Arch Insurance (UK) Ltd",
                "Scott v Copenhagen Reinsurance Co (UK) Ltd",
                "Caudle v Sharp",
                "Spire Healthcare Ltd v Royal & Sun Alliance Insurance Ltd",
            ],
            "confidence": {
                "score": 0.9,
                "level": "high",
                "notes": "Spurious historical judges removed; Males LJ gave lead judgment with Newey LJ and Flaux C agreeing.",
            },
            "storyline": {
                "title": "Restaurant chain loses COVID insurance aggregation fight",
                "summary": "Various Eateries claimed massive pandemic BI losses but Allianz capped liability at £2.5m via a single-occurrence clause tied to Wuhan. The Court of Appeal upheld remoteness findings and rejected per-restaurant aggregation, while confirming cover for closures starting within the policy year.",
                "span": {"start": "2019-09-29", "end": "2024-01-01", "label": "September 2019 – January 2024"},
                "parties": [
                    {"role": "claimant", "name": "Various Eateries Trading Ltd", "short_name": "VE"},
                    {"role": "defendant", "name": "Allianz Insurance Plc", "short_name": "Allianz"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "policy-incepted", "order": 1, "date": "2019-09-29", "date_label": "29 September 2019", "date_precision": "exact", "title": "Marsh Resilience policy period begins", "category": "factual", "actor": "VE / Allianz", "what_happened": "BI policy on Marsh Resilience Form covering ten restaurant locations.", "why_it_matters": "Defined Period of Insurance and SBIL limits.", "legal_hook": None},
                    {"id": "covid-uk", "order": 2, "date": "2020-01-30", "date_label": "January–March 2020", "date_precision": "approximate", "title": "COVID-19 reaches UK; trade falls", "category": "factual", "actor": "Public / Government", "what_happened": "Pandemic spread; VE pleaded reduced footfall from late February 2020.", "why_it_matters": "Background to BI claim and aggregation debate.", "legal_hook": None},
                    {"id": "govt-closures", "order": 3, "date": "2020-03-20", "date_label": "16–20 March 2020", "date_precision": "exact", "title": "Government closes restaurants", "category": "decision", "actor": "UK Government", "what_happened": "Social distancing guidance then mandatory closure Regulations issued.", "why_it_matters": "Butcher J treated these as relevant single occurrences.", "legal_hook": "Health Protection Regulations 2020"},
                    {"id": "allianz-payment", "order": 4, "date": None, "date_label": "Before trial", "date_precision": "unknown", "title": "Allianz pays £2.5m cap", "category": "factual", "actor": "Allianz", "what_happened": "Insurer paid largest applicable SBIL limit on Wuhan single-occurrence theory.", "why_it_matters": "VE pursued balance exceeding cap.", "legal_hook": "Single Business Interruption Loss"},
                    {"id": "preliminary-trial", "order": 5, "date": None, "date_label": "Butcher J trial", "date_precision": "unknown", "title": "Preliminary issues trial", "category": "decision", "actor": "Butcher J", "what_happened": "Judge tried aggregation, per-location and prevention-of-access construction issues.", "why_it_matters": "Found Wuhan too remote; rejected per-location aggregation.", "legal_hook": "FCA v Arch"},
                    {"id": "allianz-appeal", "order": 6, "date": None, "date_label": "Allianz appeal", "date_precision": "unknown", "title": "Allianz challenges remoteness finding", "category": "procedural", "actor": "Allianz", "what_happened": "Appeal argued Wuhan initial infection not too remote for aggregation.", "why_it_matters": "Sought to maintain £2.5m cap on full claim.", "legal_hook": None},
                    {"id": "ve-cross-appeal", "order": 7, "date": None, "date_label": "VE cross-appeal", "date_precision": "unknown", "title": "VE seeks per-location aggregation", "category": "procedural", "actor": "VE", "what_happened": "Cross-appeal for separate £2.5m limit per restaurant.", "why_it_matters": "Would multiply recoverable BI limits.", "legal_hook": None},
                    {"id": "both-dismissed", "order": 8, "date": None, "date_label": "[2024] EWCA Civ 10", "date_precision": "unknown", "title": "Court of Appeal dismisses both appeals", "category": "outcome", "actor": "Court of Appeal (Males, Newey LJJ; Flaux C)", "what_happened": "Wuhan remoteness upheld; business-wide aggregation; prevention of access scope confirmed.", "why_it_matters": "VE remains capped absent proof of separate government occurrences.", "legal_hook": "Scott v Copenhagen Re"},
                ],
                "turning_points": [
                    {"stage_id": "govt-closures", "label": "Meaningful aggregating events", "impact": "Shifted focus from Wuhan virology to UK government response."},
                    {"stage_id": "both-dismissed", "label": "£2.5m cap framework stands", "impact": "Rejected VE's per-premises multiplication of limits."},
                ],
                "confidence": {"score": 0.86, "level": "high", "notes": "Policy and March 2020 dates explicit; trial and appeal hand-down dates not stated."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/12.json",
        "judges": ["Lord Justice Lewis", "Lord Justice William Davis", "Lord Justice Coulson"],
        "enrichment": {
            "short_title": "Judicial review of East Anglia offshore wind development consent orders",
            "area_of_law": ["Planning law", "Environmental law", "Judicial review", "Infrastructure consent"],
            "statutes_considered": [
                {"title": "Planning Act 2008", "provisions": ["section 104", "section 114", "section 118"]},
                {"title": "Infrastructure Planning (Environmental Impact Assessment) Regulations 2017", "provisions": ["Schedule 4"]},
                {"title": "Conservation of Habitats and Species Regulations 2017", "provisions": ["regulation 63"]},
            ],
            "key_facts": [
                "Secretary of State granted DCOs on 31 March 2022 for EA1N and EA2 offshore wind farms and grid connections.",
                "Suffolk Alliance for Sustainable Environment (SASES) challenged surface water drainage sequential test and cumulative impact assessment.",
                "Lang J refused permission on most grounds; limited permission granted on surface water and cumulative impacts.",
                "Court of Appeal dismissed appeal; deferred Nautilus/Eurolink cumulative impact arguments pending Supreme Court.",
            ],
            "procedural_posture": "Appeal with permission on limited grounds from Lang J's refusal of JR of two development consent orders.",
            "outcome": "Appeal dismissed; sequential test for surface water not required; cumulative impact assessment adequate subject to pending Supreme Court authority.",
            "ratio": "For Schedule 4 surface water drainage under the 2017 EIA Regulations, a sequential test is not mandatory where the environmental statement addresses alternative locations and the examiner's recommendation is lawful. Cumulative impact assessment need not treat every nearby project as in-scope where effects are not significant; Nautilus/Eurolink issues deferred.",
            "legal_issues": [
                "Whether sequential test required for surface water drainage in EIA",
                "Adequacy of cumulative impact assessment for nearby wind and grid projects",
                "Whether Lang J erred in refusing permission on other grounds",
            ],
            "catchwords": ["development consent order", "offshore wind", "EIA", "surface water drainage", "sequential test", "cumulative impacts", "judicial review"],
            "index_terms": ["East Anglia One North", "East Anglia Two", "SASES", "Friston substation", "National Grid"],
            "linked_authorities": ["R (Mott) v Environment Agency", "R (ClientEarth) v Secretary of State"],
            "confidence": {
                "score": 0.87,
                "level": "high",
                "notes": "Empty judges array corrected to Lewis, William Davis and Coulson LJJ from judgment.",
            },
            "storyline": {
                "title": "Campaign group fails to overturn East Anglia wind farm consents",
                "summary": "SASES challenged DCOs for two major offshore wind projects and onshore substations at Friston. The Court of Appeal upheld the Secretary of State on surface water EIA and cumulative impact assessment, keeping the consents in place.",
                "span": {"start": "2022-03-31", "end": "2024-01-01", "label": "March 2022 – January 2024"},
                "parties": [
                    {"role": "appellant", "name": "Suffolk Alliance for Sustainable Environment", "short_name": "SASES"},
                    {"role": "respondent", "name": "Secretary of State for Business, Energy and Industrial Strategy", "short_name": "SSBEIS"},
                    {"role": "promoter", "name": "ScottishPower Renewables / SSEN", "short_name": "Promoters"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "examination", "order": 1, "date": None, "date_label": "Before March 2022", "date_precision": "unknown", "title": "NSIP examination of EA1N and EA2", "category": "institutional", "actor": "Examining Authority", "what_happened": "Examination considered offshore wind, grid connection and Friston substation impacts.", "why_it_matters": "Generated environmental statement and examiner's report.", "legal_hook": "Planning Act 2008"},
                    {"id": "dcos-made", "order": 2, "date": "2022-03-31", "date_label": "31 March 2022", "date_precision": "exact", "title": "Secretary of State makes DCOs", "category": "decision", "actor": "Secretary of State", "what_happened": "Development consent orders granted for EA1N and EA2 projects.", "why_it_matters": "Decision under challenge.", "legal_hook": "Section 114 Planning Act 2008"},
                    {"id": "jr-issued", "order": 3, "date": None, "date_label": "After March 2022", "date_precision": "unknown", "title": "SASES brings section 118 JR", "category": "procedural", "actor": "SASES", "what_happened": "Claim for judicial review of both DCOs on multiple planning grounds.", "why_it_matters": "Started litigation pathway.", "legal_hook": "Section 118"},
                    {"id": "lang-permission", "order": 4, "date": None, "date_label": "Lang J decision", "date_precision": "unknown", "title": "Limited permission granted", "category": "decision", "actor": "Lang J", "what_happened": "Permission on surface water sequential test and cumulative impacts; other grounds refused.", "why_it_matters": "Narrowed appeal scope.", "legal_hook": None},
                    {"id": "lang-dismissal", "order": 5, "date": None, "date_label": "Lang J substantive judgment", "date_precision": "unknown", "title": "Lang J refuses JR", "category": "decision", "actor": "Lang J", "what_happened": "Judge upheld DCOs on permitted grounds.", "why_it_matters": "First-instance rejection of SASES case.", "legal_hook": "EIA Regulations 2017"},
                    {"id": "ca-permission", "order": 6, "date": None, "date_label": "Before appeal", "date_precision": "unknown", "title": "Permission to appeal granted", "category": "procedural", "actor": "Court of Appeal", "what_happened": "Appeal limited to surface water and cumulative impact grounds.", "why_it_matters": "Enabled Court of Appeal review.", "legal_hook": None},
                    {"id": "nautilus-deferred", "order": 7, "date": None, "date_label": "During appeal", "date_precision": "unknown", "title": "Nautilus/Eurolink points deferred", "category": "procedural", "actor": "Court of Appeal", "what_happened": "Court deferred some cumulative impact arguments pending Supreme Court.", "why_it_matters": "Preserved live issues without overturning DCOs now.", "legal_hook": None},
                    {"id": "appeal-dismissed", "order": 8, "date": None, "date_label": "[2024] EWCA Civ 12", "date_precision": "unknown", "title": "Appeal dismissed", "category": "outcome", "actor": "Court of Appeal (Lewis, William Davis, Coulson LJJ)", "what_happened": "Sequential test not required; cumulative assessment lawful on current law.", "why_it_matters": "EA1N and EA2 DCOs remain effective.", "legal_hook": "Schedule 4 EIA Regulations"},
                ],
                "turning_points": [
                    {"stage_id": "lang-permission", "label": "Narrow JR window", "impact": "Most SASES grounds excluded before appeal."},
                    {"stage_id": "appeal-dismissed", "label": "Wind farm consents stand", "impact": "Major offshore infrastructure proceeds subject to deferred issues."},
                ],
                "confidence": {"score": 0.82, "level": "high", "notes": "31 March 2022 DCO date explicit; JR and appeal dates not stated in source."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/13.json",
        "judges": ["Lord Justice Newey", "Lord Justice Nugee", "Lord Justice Peter Jackson"],
        "enrichment": {
            "short_title": "Charity power to authorise covenant breach via paragraph 11",
            "area_of_law": ["Property law", "Restrictive covenants", "Charity law", "Land registration"],
            "statutes_considered": [
                {"title": "Law of Property Act 1925", "provisions": ["section 84"]},
                {"title": "Charities Act 2011", "provisions": ["section 117"]},
            ],
            "key_facts": [
                "Whitgift Foundation sold land in Selsdon Road, Croydon subject to restrictive covenants including a building line.",
                "Infinity Homes obtained planning permission to replace 444 Selsdon Road with nine flats breaching the covenant.",
                "Foundation executed a Deed of Modification under paragraph 11 of the Third Schedule authorising the development.",
                "Neighbour Mackenzie challenged the Foundation's power; first instance and Court of Appeal upheld the Deed.",
            ],
            "procedural_posture": "Appeal by Mr Mackenzie from Master Price's decision upholding the Whitgift Foundation's Deed of Modification.",
            "outcome": "Appeal dismissed; paragraph 11 Third Schedule empowers Foundation to authorise covenant departures; Deed of Modification effective.",
            "ratio": "Paragraph 11 of the Third Schedule to the 1925 conveyance from the Whitgift Educational Foundation confers power on the Foundation to authorise owners to depart from restrictive covenants for the benefit of the charity's purposes, without requiring section 84 LPA 1925 discharge. The Deed of Modification was within that power.",
            "legal_issues": [
                "Construction of paragraph 11 Third Schedule power",
                "Whether charity needed section 84 discharge or Charity Commission consent",
                "Effect of Deed of Modification on neighbouring owner Mackenzie's rights",
            ],
            "catchwords": ["restrictive covenant", "charity land", "Deed of Modification", "paragraph 11", "building line", "planning permission"],
            "index_terms": ["Whitgift Foundation", "Selsdon Road Croydon", "Infinity Homes", "Mackenzie", "Cheung"],
            "linked_authorities": ["Re Pinewood Estate", "Re French's Estate"],
            "confidence": {
                "score": 0.89,
                "level": "high",
                "notes": "Spurious Hoffmann, Hodge and Denning metadata removed; Newey LJ gave lead judgment.",
            },
            "storyline": {
                "title": "Charity authorises flat development despite historic covenant",
                "summary": "When a developer planned nine flats at 444 Selsdon Road, the Whitgift Foundation invoked a historic paragraph 11 power to authorise breach of a building-line covenant. Neighbour Mackenzie's challenge failed in the Court of Appeal.",
                "span": {"start": "1925-01-01", "end": "2024-01-01", "label": "1925 – January 2024"},
                "parties": [
                    {"role": "appellant", "name": "Neil Mackenzie", "short_name": "Mackenzie"},
                    {"role": "first respondent", "name": "Sharon Cheung", "short_name": "Cheung"},
                    {"role": "second respondent", "name": "Infinity Homes & Developments Ltd", "short_name": "Infinity"},
                    {"role": "foundation", "name": "The Whitgift Foundation", "short_name": "Foundation"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "original-sale", "order": 1, "date": "1925-01-01", "date_label": "1920s", "date_precision": "approximate", "title": "Foundation sells with covenants", "category": "factual", "actor": "Whitgift Educational Foundation", "what_happened": "Land sold subject to Third Schedule restrictions including building line.", "why_it_matters": "Created paragraph 11 modification power.", "legal_hook": "Third Schedule paragraph 11"},
                    {"id": "planning-permission", "order": 2, "date": None, "date_label": "Before 2022", "date_precision": "unknown", "title": "Planning permission for nine flats", "category": "decision", "actor": "Local planning authority", "what_happened": "Infinity obtained permission to demolish 444 and build flat block.", "why_it_matters": "Development would breach building-line covenant.", "legal_hook": None},
                    {"id": "deed-executed", "order": 3, "date": None, "date_label": "Before Master Price", "date_precision": "unknown", "title": "Foundation executes Deed of Modification", "category": "decision", "actor": "Whitgift Foundation", "what_happened": "Foundation authorised departure from covenant under paragraph 11.", "why_it_matters": "Central act challenged by Mackenzie.", "legal_hook": "Paragraph 11 Third Schedule"},
                    {"id": "mackenzie-challenge", "order": 4, "date": None, "date_label": "Before Master Price", "date_precision": "unknown", "title": "Mackenzie challenges deed", "category": "procedural", "actor": "Mr Mackenzie", "what_happened": "Neighbour at 432 Selsdon Road argued Foundation lacked power.", "why_it_matters": "Triggered property/ch charity law dispute.", "legal_hook": None},
                    {"id": "master-upholds", "order": 5, "date": None, "date_label": "Master Price decision", "date_precision": "unknown", "title": "Master Price upholds Deed", "category": "decision", "actor": "Master Price", "what_happened": "Master held paragraph 11 empowered Foundation to authorise development.", "why_it_matters": "First-instance victory for Cheung and Infinity.", "legal_hook": None},
                    {"id": "appeal-permission", "order": 6, "date": None, "date_label": "Before Court of Appeal", "date_precision": "unknown", "title": "Mackenzie appeals", "category": "procedural", "actor": "Mr Mackenzie", "what_happened": "Appeal on construction of Foundation's covenant-modification power.", "why_it_matters": "Brought issue to Court of Appeal.", "legal_hook": None},
                    {"id": "appeal-dismissed", "order": 7, "date": None, "date_label": "[2024] EWCA Civ 13", "date_precision": "unknown", "title": "Court of Appeal dismisses appeal", "category": "outcome", "actor": "Court of Appeal (Newey, Nugee, Peter Jackson LJJ)", "what_happened": "Paragraph 11 power validly exercised; Deed of Modification effective.", "why_it_matters": "Flat development at 444 may proceed.", "legal_hook": "Paragraph 11 construction"},
                ],
                "turning_points": [
                    {"stage_id": "deed-executed", "label": "Covenant breach authorised", "impact": "Foundation invoked historic sale power rather than section 84 route."},
                    {"stage_id": "appeal-dismissed", "label": "Paragraph 11 upheld", "impact": "Confirmed charity can release covenant restrictions for permitted development."},
                ],
                "confidence": {"score": 0.83, "level": "high", "notes": "1920s covenant origin approximate; procedural dates not stated in source."},
            },
        },
    },
]
