"""Hand-crafted enrichment + storyline for EWCA Civ 2024 batch 3 (manual, not generated)."""

CASES = [
    {
        "source_path": "data/judgments/ewca/civ/2024/39.json",
        "judges": ["Lord Justice Coulson", "Lord Justice Dingemans", "Lord Justice Snowden"],
        "enrichment": {
            "short_title": "Francovich damages and NHS orthodontic procurement scoring error",
            "area_of_law": ["Public procurement", "EU/Francovich damages", "Healthcare services"],
            "statutes_considered": [
                {"title": "Public Contracts Regulations 2015", "provisions": ["Regulation 96"]},
                {"title": "Procurement Act 2023", "provisions": []},
                {"title": "Equality Act 2010", "provisions": []},
            ],
            "key_facts": [
                "Braceurself lost a close NHS orthodontic services lot to PAL by 2.25% in February 2019.",
                "The judge found a manifest scoring error on accessibility (CSD02) that would have made Braceurself the MEAT.",
                "Automatic suspension was lifted on the basis damages would be an adequate remedy.",
                "On the damages trial the judge held the breach was not sufficiently serious for Francovich damages; the Court of Appeal upheld that conclusion.",
            ],
            "procedural_posture": "Substantive appeal against dismissal of Francovich damages claim following liability findings in public procurement proceedings.",
            "outcome": "Appeal dismissed; damages claim rightly dismissed as breach not sufficiently serious.",
            "ratio": "A but-for finding that the claimant would have won the contract is not automatically decisive on Francovich sufficient seriousness; the judge was entitled to balance low culpability against drastic consequences, and erred on the stair climber point in the respondent's notice in a way that would likely have preserved the original score.",
            "legal_issues": [
                "Whether but-for contract award finding is decisive on sufficient seriousness",
                "Application of Francovich conditions to procurement marking errors",
                "Effect of manifest error on CSD02 accessibility scoring",
            ],
            "catchwords": ["Francovich damages", "public procurement", "sufficiently serious breach", "PCR 2015", "MEAT", "automatic suspension"],
            "index_terms": ["Braceurself", "NHS England", "orthodontic services", "stair climber", "CSD02"],
            "linked_authorities": [
                "Energy Solutions EU Ltd v Nuclear Decommissioning Authority",
                "Lancashire Care NHS Foundation Trust v Lancashire County Council",
                "Boxxe Ltd v Secretary of State for Justice",
            ],
            "confidence": {"score": 0.9, "level": "high", "notes": "Manual enrichment from judgment full_text; judges corrected to Coulson, Dingemans and Snowden LJJ."},
            "storyline": {
                "title": "Close NHS orthodontic tender lost on one marking error, then Francovich damages refused",
                "summary": "Braceurself narrowly lost an NHS orthodontic contract, won on liability after a stair-climber scoring mistake, but failed to recover Francovich damages because the breach was not sufficiently serious. The Court of Appeal dismissed its appeal on the Francovich principles and partly upheld NHS England on the scoring error.",
                "span": {"start": "2019-02-01", "end": None, "label": "February 2019 procurement onwards"},
                "parties": [
                    {"role": "appellant", "name": "Braceurself Limited", "short_name": "Braceurself"},
                    {"role": "respondent", "name": "NHS England", "short_name": "NHS England"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "procurement", "order": 1, "date": "2019-02-01", "date_label": "February 2019", "date_precision": "month", "title": "Orthodontic lot awarded to PAL", "category": "institutional", "actor": "NHS England", "what_happened": "Nationwide orthodontic procurement completed; PAL scored 82.5% against Braceurself's 80.25%.", "why_it_matters": "Tiny margin meant minor scoring errors could change outcome.", "legal_hook": "PCR 2015"},
                    {"id": "suspension-lifted", "order": 2, "date": None, "date_label": "2019", "date_precision": "year", "title": "Automatic suspension lifted", "category": "hearing", "actor": "HHJ Bird", "what_happened": "Judge Bird lifted suspension and permitted damages claim, holding damages an adequate remedy.", "why_it_matters": "Contract proceeded while litigation continued.", "legal_hook": "Regulation 96 PCR 2015"},
                    {"id": "liability-trial", "order": 3, "date": None, "date_label": None, "date_precision": "unknown", "title": "Liability trial before Nissen KC", "category": "hearing", "actor": "Deputy High Court Judge", "what_happened": "Extensive challenges largely failed save CSD02 accessibility manifest error on stair climber.", "why_it_matters": "Established breach but not damages seriousness.", "legal_hook": "[2022] EWHC 1532 (TCC)"},
                    {"id": "meat-finding", "order": 4, "date": None, "date_label": None, "date_precision": "unknown", "title": "Braceurself would have been MEAT", "category": "decision", "actor": "Deputy High Court Judge", "what_happened": "Score increase on CSD02 would have made Braceurself successful bidder by 0.25%.", "why_it_matters": "Central but-for finding on appeal.", "legal_hook": None},
                    {"id": "damages-trial", "order": 5, "date": None, "date_label": None, "date_precision": "unknown", "title": "Damages trial on sufficient seriousness", "category": "hearing", "actor": "Deputy High Court Judge", "what_happened": "Separate hearing on whether breach met Francovich second condition.", "why_it_matters": "Low culpability weighed against extreme consequence.", "legal_hook": "Francovich damages"},
                    {"id": "damages-dismissed", "order": 6, "date": None, "date_label": None, "date_precision": "unknown", "title": "Damages claim dismissed", "category": "decision", "actor": "Deputy High Court Judge", "what_happened": "Judge balanced culpability and consequence; breach not sufficiently serious.", "why_it_matters": "Trigger for Court of Appeal appeal.", "legal_hook": None},
                    {"id": "ca-principles", "order": 7, "date": None, "date_label": None, "date_precision": "unknown", "title": "Court rejects but-for shortcut", "category": "decision", "actor": "Lord Justice Coulson", "what_happened": "Held but-for contract award is not automatically decisive on sufficient seriousness.", "why_it_matters": "Key principle for procurement Francovich claims.", "legal_hook": None},
                    {"id": "stair-climber", "order": 8, "date": None, "date_label": None, "date_precision": "unknown", "title": "Respondent's notice on stair climber upheld", "category": "decision", "actor": "Lord Justice Coulson", "what_happened": "Judge erred on legal significance of stair climber misunderstanding; score 3 likely correct.", "why_it_matters": "Undermines liability finding underpinning damages.", "legal_hook": None},
                    {"id": "outcome", "order": 9, "date": None, "date_label": None, "date_precision": "unknown", "title": "Appeal dismissed", "category": "outcome", "actor": "Court of Appeal", "what_happened": "Coulson, Dingemans and Snowden LJJ dismissed appeal.", "why_it_matters": "No Francovich damages for Braceurself.", "legal_hook": None},
                ],
                "turning_points": [
                    {"stage_id": "meat-finding", "label": "Would-have-won contract", "impact": "Appellant argued this should decide sufficient seriousness."},
                    {"stage_id": "ca-principles", "label": "Francovich balancing upheld", "impact": "Confirmed consequence alone does not satisfy second condition."},
                ],
                "confidence": {"score": 0.9, "level": "high", "notes": "Manual storyline from judgment narrative, batch 3."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/42.json",
        "judges": ["Lord Justice Nugee", "Lady Justice Asplin", "Lady Justice King"],
        "enrichment": {
            "short_title": "Joint tenancy or tenants in common for family farm freehold",
            "area_of_law": ["Trusts of land", "Co-ownership", "Family farming", "Property law"],
            "statutes_considered": [{"title": "Law of Property Act 1925", "provisions": ["section 34", "section 36", "section 76"]}],
            "key_facts": [
                "Cefn Coed Farm was bought in 1986 in the joint names of Mr and Mrs Williams and their son Dorian.",
                "The transfer contained no express declaration of beneficial interests.",
                "The judge held the property was held as beneficial tenants in common in equal shares.",
                "Dorian appealed, arguing Stack v Dowden required a joint tenancy presumption.",
            ],
            "procedural_posture": "Appeal on permission limited to whether Cefn Coed was held as joint tenants or tenants in common.",
            "outcome": "Appeal dismissed.",
            "ratio": "Where land is acquired in joint names for business purposes by partners, equity readily presumes a tenancy in common rather than survivorship; the Stack v Dowden domestic joint tenancy presumption does not apply to this commercial family farming context.",
            "legal_issues": [
                "Application of Stack v Dowden and Jones v Kernott outside domestic context",
                "Presumption of tenancy in common for business property",
                "Effect of 1988 wills treating shares as severable",
            ],
            "catchwords": ["joint tenancy", "tenants in common", "Stack v Dowden", "survivorship", "family farm", "resulting trust"],
            "index_terms": ["Cefn Coed Farm", "beneficial ownership", "partnership", "Land Registry Form 19"],
            "linked_authorities": ["Stack v Dowden", "Jones v Kernott", "Megarry & Wade"],
            "confidence": {"score": 0.92, "level": "high", "notes": "Manual enrichment; judges corrected to Nugee, Asplin and King LJJ."},
            "storyline": {
                "title": "Family farm co-ownership and the survivorship question",
                "summary": "When Cefn Coed Farm was bought in three names without a declaration of trust, the dispute was whether the Williams family held as joint tenants or tenants in common. The Court of Appeal held business-purpose acquisition pointed to tenants in common.",
                "span": {"start": "1986-03-03", "end": "2022-07-04", "label": "March 1986 purchase – July 2022 judgment"},
                "parties": [
                    {"role": "appellant", "name": "Lloyd Dorian Williams", "short_name": "Dorian"},
                    {"role": "respondent", "name": "Gerwyn Williams and Susan Ham", "short_name": "Siblings"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "partnership", "order": 1, "date": "1985-04-01", "date_label": "April 1985", "date_precision": "month", "title": "Farming partnership formed", "category": "background", "actor": "Williams family", "what_happened": "Partnership deed between parents and Dorian to run farming business.", "why_it_matters": "Commercial context of later purchase.", "legal_hook": None},
                    {"id": "purchase", "order": 2, "date": "1986-03-03", "date_label": "3 March 1986", "date_precision": "exact", "title": "Cefn Coed bought in three names", "category": "factual", "actor": "Mr and Mrs Williams and Dorian", "what_happened": "Freehold transferred jointly with mortgage; no express trust declaration.", "why_it_matters": "Created co-ownership dispute.", "legal_hook": None},
                    {"id": "wills-1988", "order": 3, "date": "1988-08-10", "date_label": "August 1988", "date_precision": "month", "title": "Mutual wills treat separate shares", "category": "factual", "actor": "Mr and Mrs Williams", "what_happened": "1988 wills left distinct shares in Cefn Coed to different children.", "why_it_matters": "Evidence against joint tenancy intention.", "legal_hook": None},
                    {"id": "severance", "order": 4, "date": "2014-03-03", "date_label": "3 March 2014", "date_precision": "exact", "title": "Notice of severance served", "category": "procedural", "actor": "Mr Williams", "what_happened": "Father severed any joint tenancy after Land Registry advice.", "why_it_matters": "Later estate planning context.", "legal_hook": None},
                    {"id": "trial", "order": 5, "date": "2022-07-04", "date_label": "4 July 2022", "date_precision": "exact", "title": "Trial judge finds tenants in common", "category": "decision", "actor": "HHJ Milwyn Jarman KC", "what_happened": "Held Cefn Coed held as beneficial tenants in common in equal shares.", "why_it_matters": "Decision under appeal.", "legal_hook": "[2022] EWHC 1717 (Ch)"},
                    {"id": "permission", "order": 6, "date": None, "date_label": None, "date_precision": "unknown", "title": "Limited permission to appeal", "category": "procedural", "actor": "Lewison LJ", "what_happened": "Permission limited to joint tenancy vs tenancy in common issue.", "why_it_matters": "Narrow appeal ground.", "legal_hook": None},
                    {"id": "stack-analysis", "order": 7, "date": None, "date_label": None, "date_precision": "unknown", "title": "Stack v Dowden distinguished", "category": "decision", "actor": "Lord Justice Nugee", "what_happened": "Domestic joint tenancy presumption not applied to business farm purchase.", "why_it_matters": "Core legal ratio.", "legal_hook": "Stack v Dowden"},
                    {"id": "business-rule", "order": 8, "date": None, "date_label": None, "date_precision": "unknown", "title": "Business property presumption applied", "category": "decision", "actor": "Court of Appeal", "what_happened": "Equity presumes tenants in common where property acquired for business.", "why_it_matters": "Survivorship rejected.", "legal_hook": None},
                    {"id": "outcome", "order": 9, "date": None, "date_label": None, "date_precision": "unknown", "title": "Appeal dismissed", "category": "outcome", "actor": "Court of Appeal", "what_happened": "Nugee, Asplin and King LJJ dismissed appeal.", "why_it_matters": "Tenants in common finding stands.", "legal_hook": None},
                ],
                "turning_points": [
                    {"stage_id": "stack-analysis", "label": "Commercial not domestic", "impact": "Rebutted joint tenancy presumption."},
                    {"stage_id": "business-rule", "label": "No survivorship in business", "impact": "Confirmed tenants in common."},
                ],
                "confidence": {"score": 0.92, "level": "high", "notes": "Manual storyline, batch 3."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/45.json",
        "judges": ["Lord Justice Newey", "Lord Justice Nugee", "Lord Justice Lewison"],
        "enrichment": {
            "short_title": "Clayton's Case running account after divorce settlement waiver",
            "area_of_law": ["Equitable accounting", "Family company disputes", "Agency", "Civil procedure"],
            "statutes_considered": [],
            "key_facts": [
                "Docklock and Christo operated a running account for rental income during a divorce asset split.",
                "Moylan LJ's 2017 order preserved claims for unaccounted rent between October 2014 and September 2016.",
                "The judge gave Christo credit for October 2014 disbursements against post-October receipts.",
                "Docklock appealed, arguing FIFO appropriation had already extinguished the pre-October sitting balance.",
            ],
            "procedural_posture": "Appeal against account sum awarded on taking of account following divorce-related waiver agreement.",
            "outcome": "Appeal allowed on first ground; sum due increased from £291,226.18 to £425,344.90.",
            "ratio": "Where parties operated a running account, October 2014 disbursements were appropriated to the £134,118.72 pre-October debt before the Moylan Order; Christo could not later reuse those payments as credits against post-October rent receipts.",
            "legal_issues": [
                "Application of Clayton's Case FIFO principle to agent running accounts",
                "Effect of Moylan Order and WCIA waiver on pre-October balances",
                "Whether October disbursements could be set against post-October receipts",
            ],
            "catchwords": ["Clayton's Case", "running account", "first in first out", "taking of account", "management agent", "set-off"],
            "index_terms": ["Docklock", "Christo", "Christoforou divorce", "sitting balance", "RIES"],
            "linked_authorities": ["Clayton's Case", "Barlow Clowes International Ltd v Vaughan", "W H Smith Travel Holdings Ltd v Twentieth Century Fox"],
            "confidence": {"score": 0.91, "level": "high", "notes": "Manual enrichment; judges corrected to Newey, Nugee and Lewison LJJ."},
            "storyline": {
                "title": "Divorce companies' rent account and Clayton's Case appropriation",
                "summary": "After a divorce order preserved rent accounting claims, Christo took credit for payments that had already cleared pre-October debt under a running account. The Court of Appeal held that inappropriate and increased the sum due to Docklock.",
                "span": {"start": "2014-06-04", "end": None, "label": "June 2014 divorce order onwards"},
                "parties": [
                    {"role": "appellant", "name": "Docklock Limited", "short_name": "Docklock"},
                    {"role": "respondent", "name": "C Christo & Co Limited", "short_name": "Christo"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "divorce", "order": 1, "date": "2014-06-04", "date_label": "4 June 2014", "date_precision": "exact", "title": "Divorce petition issued", "category": "background", "actor": "Christoforou couple", "what_happened": "Divorce and ancillary relief affecting family property companies.", "why_it_matters": "Led to asset split and preserved rent claims.", "legal_hook": None},
                    {"id": "moylan-order", "order": 2, "date": "2017-05-15", "date_label": "15 May 2017", "date_precision": "exact", "title": "Moylan LJ final order", "category": "decision", "actor": "Moylan LJ", "what_happened": "Equal division with exception for unaccounted agent rent October 2014–September 2016.", "why_it_matters": "Defined scope of account.", "legal_hook": None},
                    {"id": "wcia", "order": 3, "date": "2017-10-26", "date_label": "26 October 2017", "date_precision": "exact", "title": "Mutual waiver agreement executed", "category": "institutional", "actor": "Family companies", "what_happened": "WCIA waived inter-company claims except preserved rent and fee disputes.", "why_it_matters": "Waived pre-October balance claims formally.", "legal_hook": None},
                    {"id": "proceedings", "order": 4, "date": "2018-06-08", "date_label": "8 June 2018", "date_precision": "exact", "title": "Account proceedings issued", "category": "procedural", "actor": "Docklock", "what_happened": "Claim for account of rent received by Christo as agent.", "why_it_matters": "Started quantification litigation.", "legal_hook": None},
                    {"id": "trial", "order": 5, "date": "2021-02-19", "date_label": "19 February 2021", "date_precision": "exact", "title": "Nine-day account trial", "category": "hearing", "actor": "Tom Leech KC (Deputy Judge)", "what_happened": "Judge found £291,226.18 due after credits including October disbursements.", "why_it_matters": "Decision under appeal.", "legal_hook": None},
                    {"id": "running-account", "order": 6, "date": None, "date_label": None, "date_precision": "unknown", "title": "Running account accepted", "category": "decision", "actor": "Court of Appeal", "what_happened": "Parties agreed FIFO Clayton's Case applied to agent account.", "why_it_matters": "Foundation of appeal.", "legal_hook": "Clayton's Case"},
                    {"id": "october-payments", "order": 7, "date": "2014-10-01", "date_label": "October 2014", "date_precision": "month", "title": "October disbursements appropriated", "category": "factual", "actor": "Christo", "what_happened": "£161,854.96 payments in October 2014 cleared £134,118.72 sitting balance.", "why_it_matters": "Could not be reused as credits.", "legal_hook": None},
                    {"id": "ratio", "order": 8, "date": None, "date_label": None, "date_precision": "unknown", "title": "Waiver did not revive appropriation", "category": "decision", "actor": "Lord Justice Newey", "what_happened": "Moylan Order did not retrospectively undo FIFO discharge of pre-October debt.", "why_it_matters": "Core ratio.", "legal_hook": None},
                    {"id": "outcome", "order": 9, "date": None, "date_label": None, "date_precision": "unknown", "title": "Appeal allowed", "category": "outcome", "actor": "Court of Appeal", "what_happened": "Sum due varied to £425,344.90.", "why_it_matters": "Docklock recovered additional rent.", "legal_hook": None},
                ],
                "turning_points": [
                    {"stage_id": "running-account", "label": "FIFO applies", "impact": "Fixed chronological appropriation."},
                    {"stage_id": "outcome", "label": "Credits rejected", "impact": "Increased judgment sum."},
                ],
                "confidence": {"score": 0.91, "level": "high", "notes": "Manual storyline, batch 3."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/49.json",
        "judges": ["Lord Justice Snowden", "Lord Justice Phillips", "Lord Justice Moylan"],
        "enrichment": {
            "short_title": "TOLATA section 15(3) and minority beneficiary wishes",
            "area_of_law": ["Trusts of land", "Co-ownership", "Statutory interpretation", "Family property"],
            "statutes_considered": [
                {"title": "Trusts of Land and Appointment of Trustees Act 1996", "provisions": ["section 14", "section 15", "section 15(3)"]},
                {"title": "Insolvency Act 1986", "provisions": ["section 335A"]},
            ],
            "key_facts": [
                "Three Sussex land parcels were held on trust for Raymond Savage and his nieces and nephews.",
                "Frank ran a campsite business on part of the land and sought a pre-emption right before open sale.",
                "The district judge allowed Frank's pre-emption; HHJ Farquhar held section 15(3) excluded minority wishes.",
                "The Court of Appeal restored the district judge's order.",
            ],
            "procedural_posture": "Second appeal on interpretation of TOLATA section 15(3) in financial remedy-related land sale dispute.",
            "outcome": "Appeal allowed; district judge's pre-emption order restored.",
            "ratio": "Section 15(3) TOLATA obliges the court to have regard to majority wishes in a dispute but does not exclude consideration of minority beneficiaries' circumstances and wishes; the non-exhaustive structure of section 15 permits the court to weigh all relevant factors under its section 14 discretion.",
            "legal_issues": [
                "Meaning of section 15(3) TOLATA in beneficiary disputes",
                "Whether expressio unius excludes minority wishes",
                "Application of White v White and Law Commission materials",
            ],
            "catchwords": ["TOLATA", "section 15(3)", "trust of land", "sale order", "majority wishes", "statutory interpretation"],
            "index_terms": ["Pleasant Rise", "Savage family", "pre-emption", "Bagum v Hafiz"],
            "linked_authorities": ["Bagum v Hafiz", "White v White", "Saunders v Vautier"],
            "confidence": {"score": 0.93, "level": "high", "notes": "Manual enrichment; judges corrected to Snowden, Phillips and Moylan LJJ."},
            "storyline": {
                "title": "Family land sale dispute and TOLATA minority wishes",
                "summary": "Beneficiaries disagreed on how Sussex trust land should be sold. HHJ Farquhar wrongly treated section 15(3) as excluding minority wishes; the Court of Appeal restored Frank's pre-emption order.",
                "span": {"start": None, "end": "2023-02-06", "label": "Financial remedy proceedings – February 2023"},
                "parties": [
                    {"role": "appellant", "name": "Frank Savage", "short_name": "Frank"},
                    {"role": "respondent", "name": "Raymond Savage", "short_name": "Raymond"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "trust-land", "order": 1, "date": None, "date_label": None, "date_precision": "unknown", "title": "Land held on family trust", "category": "background", "actor": "Savage family", "what_happened": "Three parcels at Pleasant Rise held for Raymond and siblings' children.", "why_it_matters": "Frank operated campsite on part.", "legal_hook": None},
                    {"id": "sale-dispute", "order": 2, "date": None, "date_label": None, "date_precision": "unknown", "title": "Beneficiaries disagree on sale method", "category": "factual", "actor": "Beneficiaries", "what_happened": "Raymond sought open market sale; Frank wanted pre-emption over Raymond's share.", "why_it_matters": "Triggered TOLATA application.", "legal_hook": "section 14 TOLATA"},
                    {"id": "district-judge", "order": 3, "date": "2022-02-23", "date_label": "23 February 2022", "date_precision": "exact", "title": "District judge grants pre-emption", "category": "decision", "actor": "DJ Owen", "what_happened": "Two-day trial; Frank given right to buy Raymond's interest before open sale.", "why_it_matters": "Considered minority and majority wishes.", "legal_hook": None},
                    {"id": "hhj-reversal", "order": 4, "date": "2023-02-06", "date_label": "6 February 2023", "date_precision": "exact", "title": "HHJ Farquhar sets aside order", "category": "decision", "actor": "HHJ Farquhar", "what_happened": "Held section 15(3) prevented regard to minority wishes; ordered open sale.", "why_it_matters": "Legal error under appeal.", "legal_hook": "section 15(3)"},
                    {"id": "permission", "order": 5, "date": None, "date_label": None, "date_precision": "unknown", "title": "Second appeal permission granted", "category": "procedural", "actor": "Lady Justice King", "what_happened": "Permission on section 15(3) interpretation only.", "why_it_matters": "Limited appeal scope.", "legal_hook": None},
                    {"id": "interpretation", "order": 6, "date": None, "date_label": None, "date_precision": "unknown", "title": "Non-exhaustive section 15 analysis", "category": "decision", "actor": "Lord Justice Snowden", "what_happened": "Section 15 lists mandatory factors but does not exclude others; minority not barred.", "why_it_matters": "Core ratio.", "legal_hook": None},
                    {"id": "white-v-white", "order": 7, "date": None, "date_label": None, "date_precision": "unknown", "title": "White v White applied", "category": "decision", "actor": "Court of Appeal", "what_happened": "Confirmed court may weigh all beneficiaries' wishes under discretion.", "why_it_matters": "Supports appellant.", "legal_hook": "White v White"},
                    {"id": "outcome", "order": 8, "date": None, "date_label": None, "date_precision": "unknown", "title": "District judge order restored", "category": "outcome", "actor": "Court of Appeal", "what_happened": "Snowden, Phillips and Moylan LJJ allowed appeal and restored pre-emption.", "why_it_matters": "Frank retains buy-out right.", "legal_hook": None},
                ],
                "turning_points": [
                    {"stage_id": "interpretation", "label": "Minority wishes not excluded", "impact": "Overturned HHJ's grammatical reading."},
                    {"stage_id": "outcome", "label": "Pre-emption restored", "impact": "Business can continue at site."},
                ],
                "confidence": {"score": 0.93, "level": "high", "notes": "Manual storyline, batch 3."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/52.json",
        "judges": ["Sir Geoffrey Vos", "Sir Julian Flaux", "Lord Justice Snowden"],
        "enrichment": {
            "short_title": "ICSID award security condition on Spain's appeal refused",
            "area_of_law": ["International arbitration", "Investment treaty", "Civil procedure", "State immunity"],
            "statutes_considered": [
                {"title": "Arbitration (International Investment Disputes) Act 1966", "provisions": ["section 1(2)"]},
            ],
            "key_facts": [
                "Spain lost an ICSID arbitration and the award was registered as a UK judgment for about €120 million.",
                "Spain appealed registration and claimants sought security for the award as a condition of appeal.",
                "Males LJ granted permission to appeal without deciding the security condition.",
                "The Court held it had jurisdiction under CPR 52.18 but no compelling reason to impose security; Spain undertook to stay Luxembourg anti-suit proceedings.",
            ],
            "procedural_posture": "Application for condition requiring Spain to pay ICSID award into court as condition of pursuing appeal from registration order.",
            "outcome": "Claimants' application dismissed; Spain may pursue appeal without paying award into court.",
            "ratio": "A respondent's PD52C statement identifying a suggested condition is not a formal application decided by the permission judge; after permission is granted CPR 52.18(1)(c) permits imposing conditions only where there is a compelling reason, which was not shown where Spain offered to stay parallel Luxembourg proceedings and claimants did not establish inability to pay.",
            "legal_issues": [
                "Jurisdiction to impose conditions after permission to appeal granted",
                "Whether PD52C statement constitutes formal security application",
                "Compelling reason test under CPR 52.18 for ICSID award security",
            ],
            "catchwords": ["ICSID", "anti-suit injunction", "security for judgment", "CPR 52.18", "permission to appeal", "Energy Charter Treaty"],
            "index_terms": ["Kingdom of Spain", "Infrastructure Services Luxembourg", "Micula", "registration order"],
            "linked_authorities": ["Micula v Romania", "Dumford Trading AG v OAO Atlantrybflot"],
            "confidence": {"score": 0.9, "level": "high", "notes": "Manual enrichment; judges corrected to Vos MR, Flaux and Snowden."},
            "storyline": {
                "title": "ICSID award enforcement and Spain's appeal security battle",
                "summary": "After an ICSID award against Spain was registered in England, the investors sought to require Spain to pay €120m into court before appealing. The Court of Appeal found jurisdiction but refused security, accepting Spain's undertaking to stay Luxembourg proceedings.",
                "span": {"start": "2018-06-15", "end": "2023-11-08", "label": "June 2018 award – November 2023 hearing"},
                "parties": [
                    {"role": "claimant", "name": "Infrastructure Services Luxembourg SARL and others", "short_name": "Claimants"},
                    {"role": "defendant", "name": "The Kingdom of Spain", "short_name": "Spain"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "award", "order": 1, "date": "2018-06-15", "date_label": "15 June 2018", "date_precision": "exact", "title": "ICSID award against Spain", "category": "decision", "actor": "ICSID tribunal", "what_happened": "Award of about €120m for solar investment losses under Energy Charter Treaty.", "why_it_matters": "Underlying judgment debt.", "legal_hook": None},
                    {"id": "registration", "order": 2, "date": None, "date_label": "May 2023", "date_precision": "month", "title": "Award registered as UK judgment", "category": "institutional", "actor": "Cockerill J", "what_happened": "Registration order under 1966 Act; Fraser J dismissed set-aside application.", "why_it_matters": "Enforcement in England.", "legal_hook": "section 1(2) 1966 Act"},
                    {"id": "appeal-notice", "order": 3, "date": "2023-08-11", "date_label": "11 August 2023", "date_precision": "exact", "title": "Spain files appeal", "category": "procedural", "actor": "Spain", "what_happened": "Notice of appeal against registration; claimants identify security condition in statement.", "why_it_matters": "Started security dispute.", "legal_hook": "PD52C"},
                    {"id": "permission", "order": 4, "date": "2023-10-05", "date_label": "5 October 2023", "date_precision": "exact", "title": "Males LJ grants permission", "category": "decision", "actor": "Males LJ", "what_happened": "Permission granted on ICSID enforcement issues; no ruling on security.", "why_it_matters": "Left condition for later hearing.", "legal_hook": "CPR 52.6"},
                    {"id": "respondents-notice", "order": 5, "date": "2023-10-19", "date_label": "19 October 2023", "date_precision": "exact", "title": "Formal security application filed", "category": "procedural", "actor": "Claimants", "what_happened": "Respondents' notice seeking payment into court under CPR 52.18.", "why_it_matters": "Proper vehicle for condition.", "legal_hook": "CPR 52.18(1)(c)"},
                    {"id": "jurisdiction", "order": 6, "date": None, "date_label": None, "date_precision": "unknown", "title": "Court has jurisdiction", "category": "decision", "actor": "Sir Geoffrey Vos MR", "what_happened": "PD52C statement was not prior decided application; CPR 52.18 available.", "why_it_matters": "Security could be considered.", "legal_hook": None},
                    {"id": "luxembourg", "order": 7, "date": None, "date_label": None, "date_precision": "unknown", "title": "Spain offers Luxembourg stay", "category": "procedural", "actor": "Spain", "what_happened": "Undertaking to stay anti-suit proceedings in Luxembourg until UK appeal final.", "why_it_matters": "Removed compelling reason for security.", "legal_hook": None},
                    {"id": "outcome", "order": 8, "date": None, "date_label": None, "date_precision": "unknown", "title": "Security application dismissed", "category": "outcome", "actor": "Court of Appeal", "what_happened": "No compelling reason to require payment into court.", "why_it_matters": "Spain may appeal without security.", "legal_hook": None},
                ],
                "turning_points": [
                    {"stage_id": "jurisdiction", "label": "CPR 52.18 available", "impact": "Security could be considered post-permission."},
                    {"stage_id": "luxembourg", "label": "Stay undertaking", "impact": "Undercut bad-faith conduct argument."},
                ],
                "confidence": {"score": 0.9, "level": "high", "notes": "Manual storyline, batch 3."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/53.json",
        "judges": ["Lady Justice Andrews", "Lady Justice Falk", "Lord Justice Phillips"],
        "enrichment": {
            "short_title": "Legal helpline duty to notify tour operator of accident",
            "area_of_law": ["Professional negligence", "Solicitors' duty of care", "Personal injury", "Insurance notification"],
            "statutes_considered": [
                {"title": "Third Party (Rights Against Insurers) Act 1930", "provisions": []},
                {"title": "Third Party (Rights Against Insurers) Act 2010", "provisions": []},
            ],
            "key_facts": [
                "Mrs Miller broke her leg on holiday in Turkey booked with Lowcost; the injury ultimately led to amputation.",
                "On 19 May 2014 she called Irwin Mitchell's Legal Helpline and was told the limitation period was three years.",
                "Lowcost was notified to HCC only in March 2016; HCC declined cover for late notification.",
                "The judge found no duty to advise notification before retainer; the Court of Appeal agreed and dismissed the appeal.",
            ],
            "procedural_posture": "Appeal against dismissal of professional negligence claim after preliminary issues trial.",
            "outcome": "Appeal dismissed.",
            "ratio": "Irwin Mitchell assumed a limited duty of care when giving preliminary helpline advice, but advising on the limitation period did not extend that duty to telling a prospective client to notify the tour operator so its insurers might respond; notification was not a step Mrs Miller had to take to preserve her cause of action.",
            "legal_issues": [
                "Assumption of responsibility on legal helpline without retainer",
                "Scope of duty when limitation period advice given",
                "Construction of insurance excess clause and loss of chance",
            ],
            "catchwords": ["professional negligence", "legal helpline", "assumption of responsibility", "insurance notification", "package holiday", "limitation period"],
            "index_terms": ["Irwin Mitchell", "Lowcostholidays", "HCC International", "Spire Property Development"],
            "linked_authorities": ["Spire Property Development LLP v Withers LLP", "Crossan v Ward Bracewell & Co", "Phillips & Co v Whatley"],
            "confidence": {"score": 0.92, "level": "high", "notes": "Manual enrichment; judges corrected to Andrews, Falk and Phillips."},
            "storyline": {
                "title": "Holiday injury, late insurer notice, and helpline advice limits",
                "summary": "After a serious Turkey holiday injury, Mrs Miller called Irwin Mitchell's helpline but Lowcost's insurer was notified too late. She sued the solicitors; the Court of Appeal held the helpline owed no duty to advise immediate notification to the tour operator.",
                "span": {"start": "2014-05-13", "end": "2022-07-27", "label": "May 2014 accident – July 2022 order"},
                "parties": [
                    {"role": "claimant", "name": "Carol Miller", "short_name": "Mrs Miller"},
                    {"role": "defendant", "name": "Irwin Mitchell LLP", "short_name": "Irwin Mitchell"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "accident", "order": 1, "date": "2014-05-13", "date_label": "13 May 2014", "date_precision": "exact", "title": "Open fracture on hotel stairs", "category": "factual", "actor": "Mrs Miller", "what_happened": "Fell on Turkey package holiday; emergency surgery; later amputation in UK.", "why_it_matters": "Underlying PI claim against Lowcost.", "legal_hook": None},
                    {"id": "helpline", "order": 2, "date": "2014-05-19", "date_label": "19 May 2014", "date_precision": "exact", "title": "Legal Helpline call", "category": "factual", "actor": "Irwin Mitchell", "what_happened": "Preliminary advice given including three-year limitation period; no notification advice.", "why_it_matters": "Central alleged breach.", "legal_hook": None},
                    {"id": "retainer", "order": 3, "date": "2016-01-25", "date_label": "25 January 2016", "date_precision": "exact", "title": "Implied retainer begins", "category": "procedural", "actor": "Irwin Mitchell", "what_happened": "Retainer found from January 2016 when CFA sent; letter of claim February 2016.", "why_it_matters": "Earlier period without full retainer.", "legal_hook": None},
                    {"id": "late-notice", "order": 4, "date": "2016-03-03", "date_label": "3 March 2016", "date_precision": "exact", "title": "HCC notified of claim", "category": "institutional", "actor": "Lowcost", "what_happened": "Insurer notified over 21 months after accident; declined cover April 2016.", "why_it_matters": "Lowcost entered administration; no recovery.", "legal_hook": None},
                    {"id": "preliminary-trial", "order": 5, "date": "2022-07-27", "date_label": "27 July 2022", "date_precision": "exact", "title": "Preliminary issues trial", "category": "hearing", "actor": "HHJ Cadwallader", "what_happened": "Judge dismissed claim; no helpline duty to advise notification.", "why_it_matters": "Decision under appeal.", "legal_hook": None},
                    {"id": "spire", "order": 6, "date": None, "date_label": None, "date_precision": "unknown", "title": "Limited helpline duty accepted", "category": "decision", "actor": "Lady Justice Andrews", "what_happened": "Assumption of responsibility for preliminary advice but not tour operator notification.", "why_it_matters": "Narrows scope of liability.", "legal_hook": "Spire v Withers"},
                    {"id": "crossan", "order": 7, "date": None, "date_label": None, "date_precision": "unknown", "title": "Crossan distinguished", "category": "decision", "actor": "Court of Appeal", "what_happened": "No obligation to advise steps affecting defendant's insurance only.", "why_it_matters": "Rejects appellant's analogy.", "legal_hook": "Crossan v Ward Bracewell"},
                    {"id": "outcome", "order": 8, "date": None, "date_label": None, "date_precision": "unknown", "title": "Appeal dismissed", "category": "outcome", "actor": "Court of Appeal", "what_happened": "Andrews, Falk and Phillips LJJ dismissed appeal.", "why_it_matters": "Mrs Miller cannot recover from solicitors.", "legal_hook": None},
                ],
                "turning_points": [
                    {"stage_id": "helpline", "label": "Limitation advice only", "impact": "Defined scope of assumed duty."},
                    {"stage_id": "late-notice", "label": "Cover declined", "impact": "Created unrecoverable loss."},
                ],
                "confidence": {"score": 0.92, "level": "high", "notes": "Manual storyline, batch 3."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/64.json",
        "judges": ["Lord Justice Males", "Lord Justice Lewis", "Lord Justice Bean"],
        "enrichment": {
            "short_title": "Anti-suit injunction restraining Russian bond proceedings",
            "area_of_law": ["International arbitration", "Conflict of laws", "Anti-suit injunctions", "Sanctions"],
            "statutes_considered": [
                {"title": "Arbitration Act 1996", "provisions": ["section 7", "section 44"]},
                {"title": "Senior Courts Act 1981", "provisions": ["section 37"]},
            ],
            "key_facts": [
                "UniCredit issued on-demand bonds with English law and ICC arbitration in Paris for Russian LNG projects.",
                "After EU sanctions, RCA terminated contracts and sued UniCredit in Russian Arbitrazh Court for bond payment.",
                "Teare J held English court lacked jurisdiction; the Court of Appeal reversed and granted mandatory final anti-suit injunction.",
                "Russian Article 248.1 was invoked to declare the arbitration agreement unenforceable.",
            ],
            "procedural_posture": "Appeal against refusal of final anti-suit injunction restraining Russian court proceedings pending ICC arbitration.",
            "outcome": "Appeal allowed; English court has jurisdiction; mandatory final anti-suit injunction granted.",
            "ratio": "Where bonds are governed by English law, the arbitration agreement is governed by English law notwithstanding Paris seat; England is the proper forum because only the English court can grant an anti-suit injunction and substantial justice could not be obtained in France given Russia's Article 248.1 regime; RCA must terminate Russian proceedings.",
            "legal_issues": [
                "Governing law of arbitration agreement under Enka principles",
                "Appropriate forum for anti-suit injunction with foreign seat",
                "Whether final anti-suit injunction should be granted against sovereign",
            ],
            "catchwords": ["anti-suit injunction", "ICSID", "ICC arbitration", "Enka", "Article 248.1", "on-demand bond", "governing law"],
            "index_terms": ["UniCredit", "RusChemAlliance", "Deutsche Bank", "Paris seat", "sanctions"],
            "linked_authorities": ["Enka Insaat Ve Sanayi AS v OOO Insurance Company Chubb", "Deutsche Bank AG v RusChemAlliance LLC", "AES Ust-Kamenogorsk Hydropower Plant LLP v Ust-Kamenogorsk Hydropower Plant JSC"],
            "confidence": {"score": 0.91, "level": "high", "notes": "Manual enrichment; judges corrected to Males, Lewis and Bean LJJ."},
            "storyline": {
                "title": "Sanctions bonds, Russian court proceedings, and English anti-suit relief",
                "summary": "UniCredit refused payment under English-law bonds citing EU sanctions; RCA sued in Russia. The Court of Appeal held the arbitration agreement was English law governed and ordered RCA to end Russian proceedings.",
                "span": {"start": "2021-07-01", "end": "2024-01-29", "label": "July 2021 contracts – January 2024 injunction"},
                "parties": [
                    {"role": "appellant", "name": "UniCredit Bank GmbH", "short_name": "UniCredit"},
                    {"role": "respondent", "name": "RusChemAlliance LLC", "short_name": "RCA"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "bonds", "order": 1, "date": "2021-07-01", "date_label": "July–September 2021", "date_precision": "month", "title": "On-demand bonds issued", "category": "background", "actor": "UniCredit", "what_happened": "Seven bonds with English law and ICC Paris arbitration for LNG/GPP projects.", "why_it_matters": "Arbitration clause central to dispute.", "legal_hook": None},
                    {"id": "sanctions", "order": 2, "date": "2022-02-01", "date_label": "February 2022", "date_precision": "month", "title": "Ukraine invasion and EU sanctions", "category": "factual", "actor": "European Union", "what_happened": "Contractor halted work; RCA terminated and demanded bond payment.", "why_it_matters": "UniCredit refused citing sanctions.", "legal_hook": "Regulation (EU) 833/2014"},
                    {"id": "russia-claim", "order": 3, "date": "2023-08-05", "date_label": "5 August 2023", "date_precision": "exact", "title": "RCA sues in Russian court", "category": "procedural", "actor": "RCA", "what_happened": "Claim in St Petersburg Arbitrazh Court for about €444m bond payment.", "why_it_matters": "Breached arbitration agreement.", "legal_hook": "Article 248.1 APC RF"},
                    {"id": "interim-injunction", "order": 4, "date": "2023-08-24", "date_label": "24 August 2023", "date_precision": "exact", "title": "Interim anti-suit injunction", "category": "decision", "actor": "Robin Knowles J", "what_happened": "Urgent without-notice interim injunction restraining Russian proceedings.", "why_it_matters": "Preserved status quo pending trial.", "legal_hook": None},
                    {"id": "teare-refusal", "order": 5, "date": "2023-09-22", "date_label": "22 September 2023", "date_precision": "exact", "title": "Teare J refuses final relief", "category": "decision", "actor": "Sir Nigel Teare", "what_happened": "Held no jurisdiction; French law governed arbitration agreement; forum non conveniens.", "why_it_matters": "Decision reversed on appeal.", "legal_hook": None},
                    {"id": "enka-law", "order": 6, "date": None, "date_label": None, "date_precision": "unknown", "title": "English law governs arbitration clause", "category": "decision", "actor": "Lord Justice Males", "what_happened": "French curial law exception in Enka did not displace English law choice for bonds.", "why_it_matters": "Established jurisdiction gateway.", "legal_hook": "Enka"},
                    {"id": "forum", "order": 7, "date": None, "date_label": None, "date_precision": "unknown", "title": "England proper forum", "category": "decision", "actor": "Court of Appeal", "what_happened": "Only English court could grant anti-suit injunction; French arbitration illusory given Article 248.1.", "why_it_matters": "Service out permitted.", "legal_hook": "CPR 6.37"},
                    {"id": "final-injunction", "order": 8, "date": "2024-01-29", "date_label": "29 January 2024", "date_precision": "exact", "title": "Mandatory final injunction granted", "category": "outcome", "actor": "Court of Appeal", "what_happened": "RCA ordered to terminate Russian proceedings immediately; stay refused.", "why_it_matters": "Enforces arbitration bargain.", "legal_hook": "section 37 SCA 1981"},
                ],
                "turning_points": [
                    {"stage_id": "enka-law", "label": "English arbitration law", "impact": "Unlocked English jurisdiction."},
                    {"stage_id": "final-injunction", "label": "Russian proceedings stopped", "impact": "Protected arbitration route."},
                ],
                "confidence": {"score": 0.91, "level": "high", "notes": "Manual storyline, batch 3."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/65.json",
        "judges": ["Lord Justice Phillips", "Lord Justice Arnold", "Lord Justice Peter Jackson"],
        "enrichment": {
            "short_title": "Section 25 freezing order duration — DIFC claim meaning",
            "area_of_law": ["Freezing injunctions", "Conflict of laws", "Fraud", "Cross-border enforcement"],
            "statutes_considered": [
                {"title": "Civil Jurisdiction and Judgments Act 1982", "provisions": ["section 25"]},
            ],
            "key_facts": [
                "GFH obtained a section 25 freezing order in support of DIFC fraud proceedings against Mr Haigh.",
                "The order restrained Mr Haigh until disposal of 'the Claim' or further order.",
                "Andrew Baker J held 'the Claim' meant the DIFC proceedings, so the injunction expired on DIFC judgment in July 2018.",
                "The Court of Appeal dismissed GFH's appeal 2-1; Phillips and Peter Jackson LJJ preferred DIFC reference in paragraph 3.",
            ],
            "procedural_posture": "Appeal on construction of freezing order duration in section 25 supporting proceedings.",
            "outcome": "Appeal dismissed (majority); freezing injunction held to have expired on DIFC judgment.",
            "ratio": "In a section 25 order where paragraph 3 identifies the DIFC claim and defines the primary court's role, 'the Claim' in the duration clause naturally refers to that DIFC substantive claim rather than the English Part 8 claim, and the injunction expired automatically on final DIFC judgment.",
            "legal_issues": [
                "Construction of 'the Claim' in freezing order duration clause",
                "Whether disposal means DIFC judgment or English Part 8 disposal",
                "Effect of differing duration for ancillary defendants",
            ],
            "catchwords": ["freezing injunction", "section 25", "DIFC", "construction of order", "Ablyazov", "enforcement principle"],
            "index_terms": ["GFH Capital", "David Lawrence Haigh", "Males J", "Flaux J", "Sans Souci"],
            "linked_authorities": ["JSC BTA Bank v Ablyazov (No 10)", "Credit Suisse Fides Trust SA v Cuoghi", "Sans Souci Ltd v VRL Services Ltd"],
            "confidence": {"score": 0.89, "level": "high", "notes": "Manual enrichment; split 2-1 appeal; judges corrected."},
            "storyline": {
                "title": "DIFC fraud claim and when the English freezing order expired",
                "summary": "GFH secured a section 25 freezing order supporting DIFC proceedings against Mr Haigh. Years later he argued it had expired on DIFC judgment; the majority agreed, dismissing GFH's appeal.",
                "span": {"start": "2014-08-13", "end": "2022-11-11", "label": "August 2014 order – November 2022 application"},
                "parties": [
                    {"role": "appellant", "name": "GFH Capital Limited", "short_name": "GFH"},
                    {"role": "respondent", "name": "David Lawrence Haigh", "short_name": "Mr Haigh"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "difc-claim", "order": 1, "date": "2014-05-28", "date_label": "28 May 2014", "date_precision": "exact", "title": "DIFC fraud claim issued", "category": "background", "actor": "GFH", "what_happened": "Proceedings alleging embezzlement of about US$5m by deputy CEO.", "why_it_matters": "Primary substantive claim.", "legal_hook": None},
                    {"id": "difc-fzo", "order": 2, "date": "2014-06-03", "date_label": "3 June 2014", "date_precision": "exact", "title": "Worldwide freezing order in DIFC", "category": "decision", "actor": "DIFC Court", "what_happened": "Sir John Chadwick granted worldwide freezing order continued June 2014.", "why_it_matters": "Primary court relief.", "legal_hook": None},
                    {"id": "section25", "order": 3, "date": "2014-08-13", "date_label": "13 August 2014", "date_precision": "exact", "title": "English section 25 order", "category": "decision", "actor": "Males J", "what_happened": "Freezing order until disposal of 'the Claim' or further order; paragraph 3 references DIFC claim.", "why_it_matters": "Construction dispute.", "legal_hook": "section 25 CJJA 1982"},
                    {"id": "variation", "order": 4, "date": "2014-12-05", "date_label": "5 December 2014", "date_precision": "exact", "title": "Flaux J varies order", "category": "procedural", "actor": "Flaux J", "what_happened": "Added ancillary defendants; same duration wording for Mr Haigh retained.", "why_it_matters": "Did not change 'the Claim' meaning.", "legal_hook": None},
                    {"id": "difc-judgment", "order": 5, "date": "2018-07-04", "date_label": "4 July 2018", "date_precision": "exact", "title": "Final DIFC judgment", "category": "decision", "actor": "Sir Jeremy Cooke", "what_happened": "Judgment for GFH on constructive trust and damages.", "why_it_matters": "Appellant says injunction expired here.", "legal_hook": None},
                    {"id": "enforcement", "order": 6, "date": "2020-05-19", "date_label": "19 May 2020", "date_precision": "exact", "title": "English enforcement judgment", "category": "decision", "actor": "Henshaw J", "what_happened": "Summary judgment enforcing DIFC judgment and tracing assets.", "why_it_matters": "Separate English proceedings continued.", "legal_hook": None},
                    {"id": "baker-j", "order": 7, "date": "2022-11-11", "date_label": "11 November 2022", "date_precision": "exact", "title": "Baker J declares order discharged", "category": "decision", "actor": "Andrew Baker J", "what_happened": "Held 'the Claim' meant DIFC claim; paragraphs 4-7 discharged July 2018.", "why_it_matters": "Decision under appeal.", "legal_hook": None},
                    {"id": "majority", "order": 8, "date": None, "date_label": None, "date_precision": "unknown", "title": "Majority dismisses appeal", "category": "decision", "actor": "Phillips and Peter Jackson LJJ", "what_happened": "Paragraph 3 DIFC reference defines 'the Claim'; automatic expiry on judgment.", "why_it_matters": "Arnold LJ dissent would have allowed appeal.", "legal_hook": None},
                    {"id": "outcome", "order": 9, "date": None, "date_label": None, "date_precision": "unknown", "title": "Appeal dismissed", "category": "outcome", "actor": "Court of Appeal", "what_happened": "Mr Haigh no longer restrained by 2014 order.", "why_it_matters": "GFH must apply afresh for post-judgment relief.", "legal_hook": None},
                ],
                "turning_points": [
                    {"stage_id": "difc-judgment", "label": "DIFC disposal", "impact": "Expiry event on majority view."},
                    {"stage_id": "majority", "label": "Claim means DIFC", "impact": "Confirmed automatic discharge."},
                ],
                "confidence": {"score": 0.89, "level": "high", "notes": "Manual storyline; 2-1 split noted."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/66.json",
        "judges": ["Lord Justice Bean", "Lord Justice Males", "Lord Justice Lewis"],
        "enrichment": {
            "short_title": "Routine redaction of junior civil servants in judicial review",
            "area_of_law": ["Public law", "Judicial review", "Duty of candour", "Open justice", "Civil procedure"],
            "statutes_considered": [],
            "key_facts": [
                "Secretaries of State disclosed 500+ pages in JR challenging HMO licensing exemption for asylum accommodation.",
                "Names of civil servants below Senior Civil Service grade were routinely redacted without explanation.",
                "Swift J ordered unredacted disclosure; the Secretaries of State appealed.",
                "The Court of Appeal dismissed the appeal, rejecting routine relevance-based redaction of names.",
            ],
            "procedural_posture": "Appeal against disclosure order requiring unredaction of civil servant names in judicial review evidence.",
            "outcome": "Appeal dismissed; routine redaction of junior civil servant names not permitted.",
            "ratio": "The duty of candour requires intelligible disclosure of decision-making documents; names of senders, recipients and participants are generally relevant context and may not be redacted as a routine class on irrelevance grounds absent good specific reason such as national security or proven safety risk.",
            "legal_issues": [
                "Whether GE Capital irrelevance redaction applies to civil servant names in JR",
                "Expectation of confidentiality for junior civil servants",
                "Chilling effect and harassment arguments",
            ],
            "catchwords": ["duty of candour", "redaction", "judicial review", "civil servants", "disclosure", "open justice"],
            "index_terms": ["HMO licensing", "asylum accommodation", "Swift J", "Treasury Solicitor guidance"],
            "linked_authorities": ["GE Capital Corporate Finance v Bankers Trust", "Tweed v Parades Commission", "R (Good Law Project) v SSHSC"],
            "confidence": {"score": 0.92, "level": "high", "notes": "Manual enrichment; judges corrected to Bean, Males and Lewis LJJ."},
            "storyline": {
                "title": "Asylum HMO challenge and civil servant anonymity redaction",
                "summary": "In judicial review of asylum accommodation licensing rules, the government redacted junior civil servants' names from disclosed documents. Swift J and the Court of Appeal held routine redaction incompatible with the duty of candour.",
                "span": {"start": None, "end": "2024-02-07", "label": "JR disclosure dispute – February 2024 hearing"},
                "parties": [
                    {"role": "appellant", "name": "Secretaries of State for the Home Department and DLUHC", "short_name": "Secretaries of State"},
                    {"role": "respondent", "name": "IAB and other claimants", "short_name": "Claimants"},
                    {"role": "intervener", "name": "JUSTICE", "short_name": "JUSTICE"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "regulations", "order": 1, "date": None, "date_label": None, "date_precision": "unknown", "title": "HMO licensing exemption challenged", "category": "background", "actor": "Claimants", "what_happened": "JR brought against regulations removing HMO licensing requirement for asylum housing.", "why_it_matters": "Substantive claim scheduled February 2024.", "legal_hook": None},
                    {"id": "disclosure", "order": 2, "date": None, "date_label": None, "date_precision": "unknown", "title": "Four tranches disclosed with redactions", "category": "institutional", "actor": "Secretaries of State", "what_happened": "Over 500 pages disclosed with junior civil servant names redacted routinely.", "why_it_matters": "Triggered disclosure dispute.", "legal_hook": "Duty of candour"},
                    {"id": "objection", "order": 3, "date": None, "date_label": None, "date_precision": "unknown", "title": "Claimants object to redactions", "category": "procedural", "actor": "Claimants", "what_happened": "Argued redactions impaired intelligibility and candour.", "why_it_matters": "Preliminary issue before merits.", "legal_hook": None},
                    {"id": "swift-j", "order": 4, "date": "2023-11-17", "date_label": "17 November 2023", "date_precision": "exact", "title": "Swift J orders unredacted disclosure", "category": "decision", "actor": "Swift J", "what_happened": "Held routine redaction impermissible; names generally relevant.", "why_it_matters": "Decision under appeal.", "legal_hook": None},
                    {"id": "appeal", "order": 5, "date": None, "date_label": None, "date_precision": "unknown", "title": "Secretaries of State appeal", "category": "procedural", "actor": "Secretaries of State", "what_happened": "Relied on GE Capital irrelevance and confidentiality expectations.", "why_it_matters": "Important procedure issue.", "legal_hook": None},
                    {"id": "cards-up", "order": 6, "date": None, "date_label": None, "date_precision": "unknown", "title": "Cards face up principle reaffirmed", "category": "decision", "actor": "Lord Justice Bean", "what_happened": "Candour requires intelligible documents; email chains anonymised harm understanding.", "why_it_matters": "Rejects class redaction.", "legal_hook": "Huddleston ex p"},
                    {"id": "guidance", "order": 7, "date": None, "date_label": None, "date_precision": "unknown", "title": "Treasury Solicitor guidance cited", "category": "decision", "actor": "Court of Appeal", "what_happened": "2010 guidance does not support routine name redaction; 2023 JR Guide agrees.", "why_it_matters": "Undermines government practice.", "legal_hook": None},
                    {"id": "outcome", "order": 8, "date": None, "date_label": None, "date_precision": "unknown", "title": "Appeal dismissed", "category": "outcome", "actor": "Court of Appeal", "what_happened": "Bean, Males and Lewis LJJ dismissed appeal.", "why_it_matters": "Unredacted names to be disclosed.", "legal_hook": None},
                ],
                "turning_points": [
                    {"stage_id": "swift-j", "label": "Redaction rejected at first instance", "impact": "Set disclosure standard."},
                    {"stage_id": "cards-up", "label": "Candour over irrelevance logic", "impact": "CA rejected broad GE Capital argument."},
                ],
                "confidence": {"score": 0.92, "level": "high", "notes": "Manual storyline, batch 3."},
            },
        },
    },
    {
        "source_path": "data/judgments/ewca/civ/2024/71.json",
        "judges": ["Lord Justice Baker", "Lord Justice Green", "Lord Justice Males"],
        "enrichment": {
            "short_title": "Care fact-finding and misuse of clarification requests",
            "area_of_law": ["Family law", "Care proceedings", "Fact-finding", "Civil procedure"],
            "statutes_considered": [{"title": "Children Act 1989", "provisions": ["section 20", "section 31", "section 31(2)", "section 32"]}],
            "key_facts": [
                "Baby Y sustained rib and leg fractures and bruising; the judge found the father inflicted all injuries.",
                "Extensive requests for clarification followed the July 2023 fact-finding judgment.",
                "The local authority appealed seeking retrial, arguing clarifications undermined findings.",
                "The Court of Appeal dismissed the appeal and gave guidance limiting clarification requests.",
            ],
            "procedural_posture": "Local authority appeal against fact-finding that father caused non-accidental injuries; challenge based on clarification responses.",
            "outcome": "Appeal dismissed; no retrial; guidance on proper use of clarification process.",
            "ratio": "Requests for clarification must address material omissions or ambiguities only, not re-argue the case; read together, the judgment and clarifications coherently find the father caused inflicted injuries through lack of care rather than deliberate malice, which is sufficient for threshold and welfare decisions.",
            "legal_issues": [
                "When clarification requests are appropriate after fact-finding",
                "Whether clarification responses undermined original findings",
                "Whether retrial required given prolonged proceedings",
            ],
            "catchwords": ["care proceedings", "fact-finding", "clarification of reasons", "English v Emery", "non-accidental injury", "threshold criteria"],
            "index_terms": ["Re I (Children)", "Re O (A Child)", "Re J P and Q", "Fage UK v Chobani"],
            "linked_authorities": ["English v Emery Reimbold & Strick", "Re I (Children)", "Re S (Split Hearing)"],
            "confidence": {"score": 0.91, "level": "high", "notes": "Manual enrichment; judges corrected to Baker, Green and Males LJJ."},
            "storyline": {
                "title": "Infant injuries, repeated clarification requests, and appeal dismissed",
                "summary": "After a 14-day fact-finding hearing the judge found the father caused Y's serious injuries. Repeated clarification requests followed; the local authority sought a retrial but the Court of Appeal dismissed the appeal and tightened clarification practice.",
                "span": {"start": "2021-09-10", "end": None, "label": "September 2021 birth – proceedings ongoing"},
                "parties": [
                    {"role": "appellant", "name": "Local authority", "short_name": "Local authority"},
                    {"role": "respondent", "name": "Y's parents", "short_name": "Parents"},
                    {"role": "child", "name": "Y", "short_name": "Y"},
                    {"role": "court", "name": "Court of Appeal (Civil Division)", "short_name": "Court of Appeal"},
                ],
                "stages": [
                    {"id": "injuries", "order": 1, "date": "2021-11-25", "date_label": "25 November 2021", "date_precision": "exact", "title": "Serious injuries discovered", "category": "factual", "actor": "Hospital", "what_happened": "Fractures and bruising found; Y taken into foster care under section 20.", "why_it_matters": "Started care proceedings.", "legal_hook": "section 20 Children Act 1989"},
                    {"id": "care-proceedings", "order": 2, "date": "2022-01-05", "date_label": "5 January 2022", "date_precision": "exact", "title": "Care proceedings issued", "category": "procedural", "actor": "Local authority", "what_happened": "ICO granted; fact-finding directed with medical experts.", "why_it_matters": "Long litigation began.", "legal_hook": None},
                    {"id": "fact-finding", "order": 3, "date": "2023-07-31", "date_label": "31 July 2023", "date_precision": "exact", "title": "14-day fact-finding judgment", "category": "hearing", "actor": "Circuit judge", "what_happened": "Oral judgment finding father perpetrator of all inflicted injuries.", "why_it_matters": "Core findings for welfare stage.", "legal_hook": "section 31"},
                    {"id": "clarifications", "order": 4, "date": None, "date_label": "August–November 2023", "date_precision": "approximate", "title": "Repeated clarification requests", "category": "procedural", "actor": "Parties' counsel", "what_happened": "Seven rounds of requests including improper re-argument and new findings sought.", "why_it_matters": "Created perceived inconsistencies.", "legal_hook": "English v Emery"},
                    {"id": "supplemental", "order": 5, "date": "2023-10-19", "date_label": "19 October 2023", "date_precision": "exact", "title": "Supplemental judgment on clarifications", "category": "decision", "actor": "Circuit judge", "what_happened": "Judge responded on failure to protect and perpetrator reasoning.", "why_it_matters": "Amplified original findings.", "legal_hook": None},
                    {"id": "nov-clarification", "order": 6, "date": "2023-11-07", "date_label": "7 November 2023", "date_precision": "exact", "title": "Further clarification on lack of care", "category": "decision", "actor": "Circuit judge", "what_happened": "Accepted injuries not deliberately inflicted but caused by inexperience and lack of care.", "why_it_matters": "Local authority says this undermines findings.", "legal_hook": "Re S (Split Hearing)"},
                    {"id": "appeal", "order": 7, "date": "2023-11-29", "date_label": "29 November 2023", "date_precision": "exact", "title": "Local authority appeals for retrial", "category": "procedural", "actor": "Local authority", "what_happened": "Sought rehearing of 14-day fact-finding before different judge.", "why_it_matters": "Would cause major delay for Y.", "legal_hook": None},
                    {"id": "guidance", "order": 8, "date": None, "date_label": None, "date_precision": "unknown", "title": "Court gives clarification guidance", "category": "decision", "actor": "Lord Justice Baker", "what_happened": "Clarifications must be material; no re-argument; single consolidated request.", "why_it_matters": "Practice direction in all but name.", "legal_hook": None},
                    {"id": "outcome", "order": 9, "date": None, "date_label": None, "date_precision": "unknown", "title": "Appeal dismissed", "category": "outcome", "actor": "Court of Appeal", "what_happened": "Findings stand; retrial disproportionate; welfare decisions to proceed.", "why_it_matters": "Y placed with grandparents under ICO.", "legal_hook": "section 32"},
                ],
                "turning_points": [
                    {"stage_id": "fact-finding", "label": "Father identified as perpetrator", "impact": "Threshold findings made."},
                    {"stage_id": "outcome", "label": "No retrial", "impact": "Proceedings can move to welfare."},
                ],
                "confidence": {"score": 0.91, "level": "high", "notes": "Manual storyline, batch 3."},
            },
        },
    },
]
